const Item = require("../models/Items");

const itemData = [
  {
    name: "Club",
    properties: ["light"],
    damage: "1d4",
    damageType: "bludgeoning",
    weaponType: "simple",
    rage: "meele",
    description: "Speak softly...",
    isWeapon: true,
    rarity: "common",
    weight: "2lb",
  },
  {
    name: "Dagger",
    properties: ["light", "finesse", "thrown"],
    damage: "1d4",
    damageType: "piercing",
    weaponType: "simple",
    rage: "meele, ranged 20/60",
    description: "Up close adn personal...",
    isWeapon: true,
    rarity: "common",
    weight: "1lb",
  },
  {
    name: "Greatclub",
    properties: ["two-handed"],
    damage: "1d8",
    damageType: "bludgeoning",
    weaponType: "simple",
    rage: "meele",
    description: "Speak even quietter...",
    isWeapon: true,
    rarity: "common",
    weight: "10lb",
  },
  {
    name: "Handaxe",
    properties: ["light", "thrown"],
    damage: "1d6",
    damageType: "slashing",
    weaponType: "simple",
    rage: "meele, ranged 20/60",
    description: "Good for splitting more than just wood.",
    isWeapon: true,
    rarity: "common",
    weight: "2lb",
  },
  {
    name: "Javelin",
    properties: ["thrown"],
    damage: "1d6",
    damageType: "piercing",
    weaponType: "simple",
    rage: "thrown 30/120",
    description: "Bring home the gold, and maybe a few heads...",
    isWeapon: true,
    rarity: "common",
    weight: "2lb",
  },
  {
    name: "Light Hammer",
    properties: ["light", "thrown"],
    damage: "1d4",
    damageType: "bludgeoning",
    weaponType: "simple",
    rage: "meele, ranged 20/60",
    description: "stop. light hammer time.",
    isWeapon: true,
    rarity: "common",
    weight: "2lb",
  },
  {
    name: "Mace",
    properties: ["light"],
    damage: "1d6",
    damageType: "bludgeoning",
    weaponType: "simple",
    rage: "meele",
    description: "A classic of henchmen across faerun",
    isWeapon: true,
    rarity: "common",
    weight: "4lb",
  },
  {
    name: "Quarterstaff",
    properties: ["versatile"],
    damage: "1d6",
    damageType: "bludgeoning",
    weaponType: "simple",
    rage: "meele",
    description: "I cast Shill-agllee, wait no shillog? wait - Shillelagh!",
    isWeapon: true,
    rarity: "common",
    weight: "4lb",
  },
  {
    name: "Sickle",
    properties: ["light"],
    damage: "1d4",
    damageType: "slashing",
    weaponType: "simple",
    rage: "meele",
    description: "A farmers best friend.",
    isWeapon: true,
    rarity: "common",
    weight: "2lb",
  },
  {
    name: "Spear",
    properties: ["thrown", "versatile"],
    damage: "1d6/id8",
    damageType: "slashing",
    weaponType: "simple",
    rage: "meele, ranged 20/60",
    description: "This end up.",
    isWeapon: true,
    rarity: "common",
    weight: "3lb",
  },
  {
    name: "Light Crossbow",
    properties: ["ammunition", "ranged", "two-handed"],
    damage: "1d8",
    damageType: "piercing",
    weaponType: "simple",
    rage: "ranged 80/320",
    description: "do I get sneak attack damage on this guy...?",
    isWeapon: true,
    rarity: "common",
    weight: "5lb",
  },
  {
    name: "Dart",
    properties: ["finesse", "thrown"],
    damage: "1d4",
    damageType: "piercing",
    weaponType: "simple",
    rage: "meele, ranged 20/60",
    description: "not always posion-tipped, but usually.",
    isWeapon: true,
    rarity: "common",
    weight: ".25lb",
  },
  {
    name: "Shortbow",
    properties: ["ammunition", "ranged", "two-handed"],
    damage: "1d6",
    damageType: "piercing",
    weaponType: "simple",
    rage: "ranged 80/320",
    description: "short bow for a short king",
    isWeapon: true,
    rarity: "common",
    weight: "2lb",
  },
  {
    name: "Sling",
    properties: ["ammunition", "ranged"],
    damage: "1d4",
    damageType: "bludgeoning",
    weaponType: "simple",
    rage: "ranged 30/120",
    description: "when you need to get biblical",
    isWeapon: true,
    rarity: "common",
    weight: "0",
  },
  {
    name: "Battleaxe",
    properties: ["versatile"],
    damage: "1d8/1d10",
    damageType: "slashing",
    weaponType: "martial",
    rage: "meele",
    description: "ax or axe?",
    isWeapon: true,
    rarity: "common",
    weight: "4lb",
  },
  {
    name: "Flail",
    properties: [""],
    damage: "1d8",
    damageType: "bludgeoning",
    weaponType: "martial",
    rage: "meele",
    description: "Good enough for the witch king good enough for me!",
    isWeapon: true,
    rarity: "common",
    weight: "2lb",
  },
  {
    name: "Glaive",
    properties: ["Heavy", "Reach", "two-handed"],
    damage: "1d10",
    damageType: "slashing",
    weaponType: "martial",
    rage: "meele",
    description: "Just screams Drow ranger no?",
    isWeapon: true,
    rarity: "common",
    weight: "6lb",
  },
  {
    name: "Greataxe",
    properties: ["Heavy", "two-handed"],
    damage: "1d12",
    damageType: "slashing",
    weaponType: "martial",
    rage: "meele",
    description: "That ol\u2019 thing? Whats so great abou-.",
    isWeapon: true,
    rarity: "common",
    weight: "7lb",
  },
  {
    name: "Greatsword",
    properties: ["Heavy", "two-handed"],
    damage: "2d6",
    damageType: "slashing",
    weaponType: "martial",
    range: "meele",
    description: "That ol\u2019 thing? Whats so great abou-.",
    isWeapon: true,
    rarity: " common",
    weight: "6lb",
  },
  {
    name: "Halberd",
    properties: ["Heavy", "two-handed", "Reach"],
    damage: "1d10",
    damageType: "slashing",
    weaponType: "martial",
    range: "meele",
    description: "Always making trip attacks.",
    isWeapon: true,
    rarity: " common",
    weight: "6lb",
  },
  {
    name: "Lance",
    properties: ["Special", "Reach"],
    damage: "1d12",
    damageType: "piercing",
    weaponType: "martial",
    range: "meele",
    description: "Not just for horses anymore!.",
    isWeapon: true,
    rarity: " common",
    weight: "6lb",
  },
  {
    name: "Longsword",
    properties: ["versatile"],
    damage: "1d8/1d10",
    damageType: "slashing",
    weaponType: "martial",
    range: "meele",
    description: "Classic for a reason",
    isWeapon: true,
    rarity: " common",
    weight: "3lb",
  },
  {
    name: "Maul",
    properties: ["Heavy", "two-handed"],
    damage: "2d6",
    damageType: "bludgeoning",
    weaponType: "martial",
    range: "meele",
    description: "bigger, better, and crits like mother.",
    isWeapon: true,
    rarity: " common",
    weight: "10lb",
  },
  {
    name: "Morningstar",
    properties: [""],
    damage: "1d8",
    damageType: "piercing",
    weaponType: "martial",
    range: "meele",
    description: "Wait was this the weapon the witch king had?",
    isWeapon: true,
    rarity: " common",
    weight: "4lb",
  },
  {
    name: "Pike",
    properties: ["Heavy", "two-handed", "Reach"],
    damage: "1d10",
    damageType: "piercing",
    weaponType: "martial",
    range: "meele",
    description:
      "how is this not a spear? No - I don't want to hear about the thirty years war.",
    isWeapon: true,
    rarity: " common",
    weight: "18lb",
  },
  {
    name: "Rapier",
    properties: ["Finesse"],
    damage: "1d8",
    damageType: "piercing",
    weaponType: "martial",
    range: "meele",
    description: "Remeber that fencing scene in the Parent Trap?",
    isWeapon: true,
    rarity: " common",
    weight: "2lb",
  },
  {
    name: "Scimitar",
    properties: ["Light", "Finesse"],
    damage: "1d6",
    damageType: "slashing",
    weaponType: "martial",
    range: "meele",
    description: "For druids who want an edge.",
    isWeapon: true,
    rarity: " common",
    weight: "3lb",
  },
  {
    name: "Shortsword",
    properties: ["Finesse", "Light"],
    damage: "1d6",
    damageType: "piercing",
    weaponType: "martial",
    range: "meele",
    description: "alwasy an off-hand never a bridesmaid.",
    isWeapon: true,
    rarity: " common",
    weight: "2lb",
  },
  {
    name: "Trident",
    properties: ["Thrown", "versatile"],
    damage: "1d6/1d8",
    damageType: "piercing",
    weaponType: "martial",
    range: "meele, ranged 20/60",
    description: "Aquaman's got nothing on me.",
    isWeapon: true,
    rarity: " common",
    weight: "4lb",
  },
  {
    name: "War Pick",
    properties: [""],
    damage: "1d8",
    damageType: "piercing",
    weaponType: "martial",
    range: "meele",
    description: "not to be confused with the war-tooth-pick",
    isWeapon: true,
    rarity: " common",
    weight: "2lb",
  },
  {
    name: "Warhammer",
    properties: ["versatile"],
    damage: "1d8/1d10",
    damageType: "bludgeoning",
    weaponType: "martial",
    range: "meele",
    description: "Seems so satisfying to swing.",
    isWeapon: true,
    rarity: " common",
    weight: "2lb",
  },
  {
    name: "Whip",
    properties: ["Finesse", "Reach"],
    damage: "1d4",
    damageType: "slashing",
    weaponType: "martial",
    range: "meele",
    description: "A Belmont classic.",
    isWeapon: true,
    rarity: " common",
    weight: "3lb",
  },
  {
    name: "Blowgun",
    properties: ["ranged"],
    damage: "1",
    damageType: "piercing",
    weaponType: "martial",
    range: "ranged 25/100",
    description: "only used to protect artifacts",
    isWeapon: true,
    rarity: " common",
    weight: "1lb",
  },
  {
    name: "Hand Crossbow",
    properties: ["ranged", "Light", "ammunition"],
    damage: "1d6",
    damageType: "piercing",
    weaponType: "martial",
    range: "ranged 30/120",
    description: "pew-pew bonus aciton",
    isWeapon: true,
    rarity: " common",
    weight: "3lb",
  },
  {
    name: "Heavy Crossbow",
    properties: ["ranged", "two-handed", "ammunition"],
    damage: "1d10",
    damageType: "piercing",
    weaponType: "martial",
    range: "ranged 100/400",
    description: "no but for real, do I get sneak-attack?",
    isWeapon: true,
    rarity: " common",
    weight: "18lb",
  },
  {
    name: "Longbow",
    properties: ["ranged", "two-handed", "ammunition"],
    damage: "1d8",
    damageType: "piercing",
    weaponType: "martial",
    range: "ranged 150/600",
    description: "again, no, I do not want to hear about the thirty years war!",
    isWeapon: true,
    rarity: " common",
    weight: "2lb",
  },
  {
    name: "Longbow",
    properties: ["ranged", "two-handed", "ammunition"],
    damage: "1d8",
    damageType: "piercing",
    weaponType: "martial",
    range: "ranged 150/600",
    description: "again, no, I do not want to hear about the thirty years war!",
    isWeapon: true,
    rarity: " common",
    weight: "2lb",
  },
  {
    name: "Padded",
    properties: ["stealth disadvantage"],
    armorType: "Light",
    description: "a little extra cushion never hurt",
    isArmor: true,
    acBonus: "11",
    dexBonus: "full",
    rarity: "common",
    weight: "8lb",
  },
  {
    name: "Leather",
    properties: [""],
    armorType: "Light",
    description: "Or pleather if your dm allows.",
    isArmor: true,
    acBonus: "11",
    dexBonus: "full",
    rarity: "common",
    weight: "10lb",
  },
  {
    name: "Studded Leather",
    properties: [""],
    armorType: "Light",
    description: "Punk rock man.",
    isArmor: true,
    acBonus: "12",
    dexBonus: "full",
    rarity: "common",
    weight: "13lb",
  },
  {
    name: "Shield",
    properties: ["Shield"],
    armorType: "Shield",
    description:
      "Styled any way you like, be it metal or wodden its still +2 to your AC unless you ask your DM.",
    isArmor: true,
    acBonus: "2",
    dexBonus: "full",
    rarity: "common",
    weight: "6lb",
  },
  {
    name: "Hide",
    properties: [""],
    armorType: "Medium",
    description: "wait, isnt leather technically a...?",
    isArmor: true,
    acBonus: "12",
    dexBonus: "2",
    rarity: "common",
    weight: "12lb",
  },
  {
    name: "Chain Shirt",
    properties: [""],
    armorType: "Medium",
    description: "They didn't have pants in my size...",
    isArmor: true,
    acBonus: "13",
    dexBonus: "2",
    rarity: "common",
    weight: "20lb",
  },
  {
    name: "Scale Mail",
    properties: ["stealth disadvantage"],
    armorType: "Medium",
    description: "Not actual scales, which would kindsa be like leather.",
    isArmor: true,
    acBonus: "14",
    dexBonus: "2",
    rarity: "common",
    weight: "45lb",
  },
  {
    name: "Spiked Armor",
    properties: ["stealth disadvantage"],
    armorType: "Medium",
    description: "For your edgy Gloomstalker Ranger.",
    isArmor: true,
    acBonus: "14",
    dexBonus: "2",
    rarity: "common",
    weight: "45lb",
  },
  {
    name: "Breast Plate",
    properties: [""],
    armorType: "Medium",
    description:
      "Not actually sure why there isn\u2019t disadvantage on stealth for this one.",
    isArmor: true,
    acBonus: "14",
    dexBonus: "2",
    rarity: "common",
    weight: "20lb",
  },
  {
    name: "Halfplate",
    properties: ["stealth disadvantage"],
    armorType: "Medium",
    description: "couldn\u2019t aford the whole plate.",
    isArmor: true,
    acBonus: "15",
    dexBonus: "2",
    rarity: "common",
    weight: "40lb",
  },
  {
    name: "Ring Mail",
    properties: ["stealth disadvantage"],
    armorType: "Heavy",
    description:
      "Functionaly worse than scale mail and twice as tedious to make.",
    isArmor: true,
    acBonus: "14",
    dexBonus: "0",
    rarity: "common",
    weight: "40lb",
  },
  {
    name: "Chain Mail",
    properties: ["stealth disadvantage", "req. STR 13"],
    armorType: "Heavy",
    description: "Also great for cleaning cast iron.",
    isArmor: true,
    acBonus: "16",
    dexBonus: "0",
    rarity: "common",
    weight: "55lb",
  },
  {
    name: "Splint",
    properties: ["stealth disadvantage", "req. STR 15"],
    armorType: "Heavy",
    description: "do not try to set a bone with this.",
    isArmor: true,
    acBonus: "17",
    dexBonus: "0",
    rarity: "common",
    weight: "60lb",
  },
  {
    name: "Plate",
    properties: ["stealth disadvantage", "req. STR 15"],
    armorType: "Heavy",
    description: 'as in "I ate the whole plate".',
    isArmor: true,
    acBonus: "18",
    dexBonus: "0",
    rarity: "common",
    weight: "65lb",
  },
  {
    name: "acid",
    properties: ["Throwable", "Improvised Weapon"],
    damage: "2d6",
    damageType: "Acid",
    range: "20/60",
    description:
      "As an action, you can splash the contents of this vial onto a creature within 5 feet of you or throw the vial up to 20 feet, shattering it on impact. In either case, make a ranged Attack against a creature or object, treating the acid as an improvised weapon. On a hit, the target takes 2d6 acid damage.",
    isItem: true,
    rarity: "common",
    weight: "1lb",
  },
  {
    name: "Alchemist\u2019s Fire (flask)",
    properties: ["Throwable", "Improvised Weapon"],
    damage: "1d4",
    damageType: "Fire",
    range: "20/60",
    description:
      "This sticky, adhesive fluid ignites when exposed to air. As an action, you can throw this flask up to 20 feet, shattering it on impact. Make a ranged Attack against a creature or object, treating the alchemist's fire as an improvised weapon. On a hit, the target takes 1d4 fire damage at the start of each of its turns. A creature can end this damage by using its action to make a DC 10 Dexterity check to extinguish the flames.",
    isItem: true,
    rarity: "common",
    weight: "1lb",
  },
  {
    name: "Alchemist\u2019s Supplies",
    properties: ["Tools"],
    description:
      "These special tools include the items needed to pursue a craft or trade. Proficiency with a set of artisan's tools lets you add your proficiency bonus to any ability checks you make using the tools in your craft. Each type of artisan's tools requires a separate proficiency.",
    isItem: true,
    rarity: "common",
    weight: "8lb",
  },
  {
    name: "Amulet",
    properties: ["Gear", "Spellcasting Focus"],
    description:
      "A holy symbol is a representation of a god or pantheon. It might be an amulet depicting a symbol representing a deity, the same symbol carefully engraved or inlaid as an emblem on a shield, or a tiny box holding a fragment of a sacred relic. Pantheons lists the symbols commonly associated with many gods in the multiverse. A cleric or paladin can use a holy symbol as a spellcasting focus. To use the symbol in this way, the caster must hold it in hand, wear it visibly, or bear it on a shield.",
    isItem: true,
    rarity: "common",
    weight: ".5lb",
  },
  {
    name: "Amulet of Health",
    properties: ["Gear", "Wondrous", "Attunement"],
    description:
      "Your Constitution score is 19 while you wear this amulet. It has no effect on you if your Constitution score is already 19 or higher.",
    isItem: true,
    rarity: "rare",
    weight: ".5lb",
  },
  {
    name: "Amulet of Proof against Detection and Location",
    properties: ["Gear", "Wondrous", "Attunement"],
    description:
      "While wearing this amulet, you are hidden from divination magic. You can't be targeted by such magic or perceived through magical scrying sensors.",
    isItem: true,
    rarity: "uncommon",
    weight: ".5lb",
  },
  {
    name: "Amulet of the Planes",
    properties: ["Gear", "Wondrous", "Attunement"],
    description:
      "While wearing this amulet, you can use an action to name a location that you are familiar with on another plane of existence. Then make a DC 15 Intelligence check. On a successful check, you cast the plane shift spell. On a failure, you and each creature and object within 15 feet of you travel to a random destination. Roll a d100. On a 1-60, you travel to a random location on the plane you named. On a 61-100, you travel to a randomly determined plane of existence.",
    isItem: true,
    rarity: "very rare",
    weight: ".5lb",
  },
  {
    name: "Animated Shield",
    properties: ["Gear", "Wondrous", "Attunement", "Shield"],
    description:
      "While holding this shield, you can speak its command word as a bonus action to cause it to animate. The shield leaps into the air and hovers in your space to protect you as if you were wielding it, leaving your hands free. The shield remains animated for 1 minute, until you use a bonus action to end this effect, or until you are incapacitated or die, at which point the shield falls to the ground or into your hand if you have one free.",
    isItem: true,
    isArmor: true,
    acBonus: "2",
    rarity: "very rare",
    weight: "6lb",
  },
  {
    name: "Antitoxin",
    properties: ["gear", "consumable"],
    description:
      "A creature that drinks this vial of liquid gains advantage on saving throws against poison for 1 hour. It confers no benefit to undead or constructs.",
    isItem: true,
    rarity: "common",
    weight: "0",
  },
  {
    name: "Armor of Invulnerability",
    properties: [
      "Gear",
      "Wondrous",
      "Attunement",
      "stealth disadvantage",
      "req. STR 15",
    ],
    armorType: "Heavy",
    description:
      "You have resistance to nonmagical damage while you wear this armor. Additionally, you can use an action to make yourself immune to nonmagical damage for 10 minutes or until you are no longer wearing the armor. Once this special action is used, it can't be used again until the next dawn.",
    isArmor: true,
    acBonus: "18",
    dexBonus: "0",
    rarity: "legendary",
    weight: "65lb",
  },
  {
    name: "Armor of Vulnerability",
    properties: [
      "Gear",
      "Wondrous",
      "Attunement",
      "stealth disadvantage",
      "req. STR 15",
    ],
    armorType: "Heavy",
    description:
      "While wearing this armor, you have resistance to one of the following damage types: bludgeoning, piercing, or slashing. The GM chooses the type or determines it randomly. Curse. This armor is cursed, a fact that is revealed only when an identify spell is cast on the armor or you attune to it. Attuning to the armor curses you until you are targeted by the remove curse spell or similar magic; removing the armor fails to end the curse. While cursed, you have vulnerability to two of the three damage types associated with the armor (not the one to which it grants resistance).",
    isArmor: true,
    acBonus: "18",
    dexBonus: "0",
    rarity: "legendary",
    weight: "65lb",
  },
  {
    name: "Arrow of Slaying",
    properties: ["ammunition", "gear"],
    description:
      "An arrow of slaying is a magic weapon meant to slay a particular kind of creature. Some are more focused than others; for example, there are both arrows of dragon slaying and arrows of blue dragon slaying. If a creature belonging to the type, race, or group associated with an arrow of slaying takes damage from the arrow, the creature must make a DC 17 Constitution saving throw, taking an extra 6d10 piercing damage on a failed save, or half as much extra damage on a successful one. Once an arrow of slaying deals its extra damage to a creature, it becomes a nonmagical arrow. Other types of magic ammunition of this kind exist, such as bolts of slaying meant for a crossbow, though arrows are most common.",
    rarity: "very rare",
    weight: ".05",
  },
  {
    name: "Arrows",
    properties: ["ammunition", "gear"],
    description:
      "You can use a weapon that has the ammunition property to make a ranged attack only if you have ammunition to fire from the weapon. Each time you attack with the weapon, you expend one piece of ammunition. Drawing the ammunition from a quiver, case, or other container is part of the attack (you need a free hand to load a one-handed weapon). At the end of the battle, you can recover half your expended ammunition by taking a minute to search the battlefield.",
    rarity: "common",
    weight: ".05",
  },
];

async function seedItems() {
  try {
    const existingItems = await Item.find({});

    for (const item of itemData) {
      const isExisting = existingItems.some(
        (existingItem) => existingItem.name === item.name
      );

      if (!isExisting) {
        await Item.create(item);
        console.log(`${item.name} created!`);
      } else {
        await Item.findOneAndUpdate({ name: item.name }, item);
        console.log(`${item.name} upated`);
      }
    }
  } catch (err) {
    console.error("Error seeding Items", err);
  }
}

module.exports = { seedItems };
