const Spell = require("../models/Spells");

const spellData = [
  {
    name: "Abi-Dalzim's Horrid Wilting",
    spellClass: ["Sorcerer", "Wizard"],
    lvl: "8",
    school: "Necormancy",
    range: "150ft/30ft cube",
    castingTime: "1 action",
    duration: "Instantaneous",
    concentration: false,
    ritual: false,
    saveThrow: "CON",
    damageType: "Necrotic",
    components: ["V", "S", "M"],
    materials: "a bit of sponge",
    description:
      "You draw the moisture from every creature in a 30-foot cube centered on a point you choose within range. Each creature in that area must make a Constitution saving throw. Constructs and undead aren\u2019t affected, and plants and water elementals make this saving throw with disadvantage. A creature takes 12d8 necrotic damage on a failed save, or half as much damage on a successful one.Nonmagical plants in the area that aren\u2109t creatures, such as trees and shrubs, wither and die instantly.",
  },

  {
    name: "Absorb Elements",
    spellClass: ["Artificer", "Wizard", "Druid", "Ranger", "Sorcerer"],
    lvl: "1",
    school: "Abjuration",
    range: "self",
    castingTime: "1 action",
    duration: "1 round",
    concentration: false,
    ritual: false,
    saveThrow: "",
    damageType: "",
    components: ["S"],
    materials: "",
    description:
      "The spell captures some of the incoming energy, lessening its effect on you and storing it for your next melee attack. You have resistance to the triggering damage type until the start of your next turn. Also, the first time you hit with a melee attack on your next turn, the target takes an extra 1d6 damage of the triggering type, and the spell ends. At Higher Levels. When you cast this spell using a spell slot of 2nd level or higher, the extra damage increases by 1d6 for each slot level above 1st.",
  },

  {
    name: "Acid Arrow",
    spellClass: ["Alchemist", "Wizard", "Druid"],
    lvl: "2",
    school: "Evocation",
    range: "90ft",
    castingTime: "1 action",
    duration: "Instantaneous",
    concentration: false,
    ritual: false,
    saveThrow: "",
    damageType: "Acid",
    components: ["V", "S", "M"],
    materials: "powdered rhubarb leaf and an adder\u2019s stomach",
    description:
      "A shimmering green arrow streaks toward a target within range and bursts in a spray of acid. Make a ranged spell attack against the target. On a hit, the target takes 4d4 acid damage immediately and 2d4 acid damage at the end of its next turn. On a miss, the arrow splashes the target with acid for half as much of the initial damage and no damage at the end of its next turn.At Higher Levels. When you cast this spell using a spell slot of 3rd level or higher, the damage (both initial and later) increases by 1d4 for each slot level above 2nd.",
  },
  {
    name: "Acid Splash",
    spellClass: ["Sorcerer", "Wizard", "Artificer"],
    lvl: "cantrip",
    school: "Conjuration",
    range: "60ft",
    castingTime: "1 action",
    duration: "Instantaneous",
    concentration: false,
    ritual: false,
    saveThrow: "",
    damageType: "Acid",
    components: ["V", "S", "M"],
    materials: "powdered rhubarb leaf and an adder\u2019s stomach",
    description:
      "A shimmering green arrow streaks toward a target within range and bursts in a spray of acid. Make a ranged spell attack against the target. On a hit, the target takes 4d4 acid damage immediately and 2d4 acid damage at the end of its next turn. On a miss, the arrow splashes the target with acid for half as much of the initial damage and no damage at the end of its next turn.At Higher Levels. When you cast this spell using a spell slot of 3rd level or higher, the damage (both initial and later) increases by 1d4 for each slot level above 2nd.",
  },
  {
    name: "Aganazzar's Scorcher",
    spellClass: ["Sorcerer", "Wizard"],
    lvl: "2",
    school: "Evocation",
    range: "30ft line",
    castingTime: "1 action",
    duration: "Instantaneous",
    concentration: false,
    ritual: false,
    saveThrow: "DEX",
    damageType: "Fire",
    components: ["V", "S", "M"],
    materials: "a red dragon\u2019s scale",
    description:
      "A line of roaring flame 30 feet long and 5 feet wide emanates from you in a direction you choose. Each creature in the line must make a Dexterity saving throw. A creature takes 3d8 fire damage on a failed save, or half as much damage on a successful one. At Higher Levels. When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d8 for each slot level above 2nd.",
  },
  {
    name: "Aid",
    spellClass: ["Arificer", "Cleric", "Paladin"],
    lvl: "2",
    school: "Abjuration",
    range: "30ft",
    castingTime: "1 action",
    duration: "8 Hours",
    concentration: false,
    ritual: false,
    saveThrow: "",
    damageType: "",
    components: ["V", "S", "M"],
    materials: "a tiny strip of white cloth",
    description:
      "Your spell bolsters your allies with toughness and resolve. Choose up to three creatures within range. Each target\u2019s hit point maximum and current hit points increase by 5 for the duration. At Higher Levels. When you cast this spell using a spell slot of 3rd level or higher, a target\u2019s hit points increase by an additional 5 for each slot level above 2nd.",
  },
  {
    name: "Air Bubble",
    spellClass: ["Arificer", "Druid", "Ranger", "Wizard", "Sorcerer"],
    lvl: "2",
    school: "Conjuration",
    range: "60ft",
    castingTime: "1 action",
    duration: "24 Hours",
    concentration: false,
    ritual: false,
    saveThrow: "",
    damageType: "",
    components: ["S"],
    materials: "",
    description:
      "You create a spectral globe around the head of a willing creature you can see within range. The globe is filled with fresh air that lasts until the spell ends. If the creature has more than one head, the globe of air appears around only one of its heads (which is all the creature needs to avoid suffocation, assuming that all its heads share the same respiratory system). At Higher Levels. When you cast this spell using a spell slot of 3rd level or higher, you can create two additional globes of fresh air for each slot level above 2nd.",
  },
  {
    name: "Alarm",
    spellClass: ["Ranger", "Wizard", "Artificer", "Oath of Watchers"],
    lvl: "1",
    school: "Abjuration",
    range: "30ft",
    castingTime: "1 minute",
    duration: "8 Hours",
    concentration: false,
    ritual: true,
    components: ["V", "S", "M"],
    materials: "a tiny bell and a piece of fine silver wire",
    description:
      "You set an alarm against unwanted intrusion. Choose a door, a window, or an area within range that is no larger than a 20-foot cube. Until the spell ends, an alarm alerts you whenever a Tiny or larger creature touches or enters the warded area. When you cast the spell, you can designate creatures that won't set off the alarm. You also choose whether the alarm is mental or audible. A mental alarm alerts you with a ping in your mind if you are within 1 mile of the warded area. This ping awakens you if you are sleeping. An audible alarm produces the sound of a hand bell for 10 seconds within 60 feet.",
  },
  {
    name: "Alter Self",
    spellClass: ["Arificer", "Wizard", "Sorcerer"],
    lvl: "2",
    school: "Transmutation",
    range: "self",
    castingTime: "1 action",
    duration: "1 hour",
    concentration: true,
    ritual: false,
    components: ["V", "S"],
    description:
      "You assume a different form. When you cast the spell, choose one of the following options, the effects of which last for the duration of the spell. While the spell lasts, you can end one option as an action to gain the benefits of a different one. Aquatic Adaptation. You adapt your body to an aquatic environment, sprouting gills and growing webbing between your fingers. You can breathe underwater and gain a swimming speed equal to your walking speed. Change Appearance. You transform your appearance. You decide what you look like, including your height, weight, facial features, sound of your voice, hair length, coloration, and distinguishing characteristics, if any. You can make yourself appear as a member of another race, though none of your statistics change. You also can't appear as a creature of a different size than you, and your basic shape stays the same; if you're bipedal, you can't use this spell to become quadrupedal, for instance. At any time for the duration of the spell, you can use your action to change your appearance in this way again. Natural Weapons. You grow claws, fangs, spines, horns, or a different natural weapon of your choice. Your unarmed strikes deal 1d6 bludgeoning, piercing, or slashing damage, as appropriate to the natural weapon you chose, and you are proficient with your unarmed strikes. Finally, the natural weapon is magic and you have a +1 bonus to the attack and damage rolls you make using it",
  },
  {
    name: "Animal Friendship",
    spellClass: ["Bard", "Druid", "Ranger", "Nature Domain"],
    lvl: "1",
    school: "Enchantment",
    range: "30ft",
    castingTime: "1 action",
    duration: "24 hours",
    concentration: false,
    ritual: false,
    saveThrow: "WIS",
    components: ["V", "S", "M"],
    materials: "a morsel of food",
    description:
      "This spell lets you convince a beast that you mean it no harm. Choose a beast that you can see within range. It must see and hear you. If the beast's Intelligence is 4 or higher, the spell fails. Otherwise, the beast must succeed on a Wisdom saving throw or be charmed by you for the spell's duration. If you or one of your companions harms the target, the spell ends. At Higher Levels. When you cast this spell using a spell slot of 2nd level or higher, you can affect one additional beast for each slot level above 1st.",
  },
  {
    name: "Animal Messenger",
    spellClass: ["Bard", "Druid", "Ranger"],
    lvl: "2",
    school: "Enchantment",
    range: "30ft",
    castingTime: "1 action",
    duration: "24 hours",
    concentration: false,
    ritual: true,
    components: ["V", "S", "M"],
    materials: "a morsel of food",
    description:
      'By means of this spell, you use an animal to deliver a message. Choose a Tiny beast you can see within range, such as a squirrel, a blue jay, or a bat. You specify a location, which you must have visited, and a recipient who matches a general description, such as "a man or woman dressed in the uniform of the town guard" or "a red-haired dwarf wearing a pointed hat." You also speak a message of up to twenty-five words. The target beast travels for the duration of the spell toward the specified location, covering about 50 miles per 24 hours for a flying messenger, or 25 miles for other animals. When the messenger arrives, it delivers your message to the creature that you described, replicating the sound of your voice. The messenger speaks only to a creature matching the description you gave. If the messenger doesn\'t reach its destination before the spell ends, the message is lost, and the beast makes its way back to where you cast this spell. At Higher Levels. If you cast this spell using a spell slot of 3rd level or higher, the duration of the spell increases by 48 hours for each slot level above 2nd.',
  },
  {
    name: "Animal Shapes",
    spellClass: ["Druid"],
    lvl: "8",
    school: "Transmutation",
    range: "30ft",
    castingTime: "1 action",
    duration: "24 hours",
    concentration: true,
    ritual: false,
    components: ["V", "S"],
    description:
      "Your magic turns others into beasts. Choose any number of willing creatures that you can see within range. You transform each target into the form of a Large or smaller beast with a challenge rating of 4 or lower. On subsequent turns, you can use your action to transform affected creatures into new forms. The transformation lasts for the duration for each target, or until the target drops to 0 hit points or dies. You can choose a different form for each target. A target's game statistics are replaced by the statistics of the chosen beast, though the target retains its alignment and Intelligence, Wisdom, and Charisma scores. The target assumes the hit points of its new form, and when it reverts to its normal form, it returns to the number of hit points it had before it transformed. If it reverts as a result of dropping to 0 hit points, any excess damage carries over to its normal form. As long as the excess damage doesn't reduce the creature's normal form to 0 hit points, it isn't knocked unconscious. The creature is limited in the actions it can perform by the nature of its new form, and it can't speak or cast spells. The target's gear melds into the new form. The target can't activate, wield, or otherwise benefit from any of its equipment.",
  },
  {
    name: "Animate Dead",
    spellClass: ["Druid", "Wizard", "Death Domain", "Wizard", "Oathbreaker"],
    lvl: "3",
    school: "Necromancy",
    range: "10ft",
    castingTime: "1 minute",
    duration: "24 hours",
    concentration: false,
    ritual: false,
    components: ["V", "S", "M"],
    materials: "a drop of blood, a piece of flesh, and a pinch of bone dust",
    description:
      "This spell creates an undead servant. Choose a pile of bones or a corpse of a Medium or Small humanoid within range. Your spell imbues the target with a foul mimicry of life, raising it as an undead creature. The target becomes a skeleton if you chose bones or a zombie if you chose a corpse (the GM has the creature's game statistics). On each of your turns, you can use a bonus action to mentally command any creature you made with this spell if the creature is within 60 feet of you (if you control multiple creatures, you can command any or all of them at the same time, issuing the same command to each one). You decide what action the creature will take and where it will move during its next turn, or you can issue a general command, such as to guard a particular chamber or corridor. If you issue no commands, the creature only defends itself against hostile creatures. Once given an order, the creature continues to follow it until its task is complete. The creature is under your control for 24 hours, after which it stops obeying any command you've given it. To maintain control of the creature for another 24 hours, you must cast this spell on the creature again before the current 24-hour period ends. This use of the spell reasserts your control over up to four creatures you have animated with this spell, rather than animating a new one. At Higher Levels. When you cast this spell using a spell slot of 4th level or higher, you animate or reassert control over two additional undead creatures for each slot level above 3rd. Each of the creatures must come from a different corpse or pile of bones.",
  },
  {
    name: "Animate Objects",
    spellClass: ["Artificer", "Wizard", "Forge Domain", "Bard", "Sorcerer"],
    lvl: "5",
    school: "Transutation",
    range: "120ft",
    castingTime: "1 action",
    duration: "1 minute",
    concentration: true,
    ritual: false,
    components: ["V", "S", "M"],
    materials: "a drop of blood, a piece of flesh, and a pinch of bone dust",
    description:
      "Objects come to life at your command. Choose up to ten nonmagical objects within range that are not being worn or carried. Medium targets count as two objects, Large targets count as four objects, Huge targets count as eight objects. You can't animate any object larger than Huge. Each target animates and becomes a creature under your control until the spell ends or until reduced to 0 hit points. As a bonus action, you can mentally command any creature you made with this spell if the creature is within 500 feet of you (if you control multiple creatures, you can command any or all of them at the same time, issuing the same command to each one). You decide what action the creature will take and where it will move during its next turn, or you can issue a general command, such as to guard a particular chamber or corridor. If you issue no commands, the creature only defends itself against hostile creatures. Once given an order, the creature continues to follow it until its task is complete. One of the following (Tiny - HP-20 AC-18 str-4 dex-18 attack +8 to hit 1d4+4 dmg)(Small - HP-25 AC-16 str-6 dex-14  attack+6 to hit, 1d8+2 dmg)(medium - HP-40 AC-13 str-10 dex-12 attack +5to hit, 2d6+1 dmg)(Large - HP-50 AC-10 str-14 dex-10 attack +6 to hit, 2d20+d dmg)(Huge - HP-80 ac-10 str-18 dex-6 attack +8to hit 2d12+4dmg)An animated object is a construct with AC, hit points, attacks, Strength, and Dexterity determined by its size. Its Constitution is 10 and its Intelligence and Wisdom are 3, and its Charisma is 1. Its speed is 30 feet; if the object lacks legs or other appendages it can use for locomotion, it instead has a flying speed of 30 feet and can hover. If the object is securely attached to a surface or a larger object, such as a chain bolted to a wall, its speed is 0. It has blindsight with a radius of 30 feet and is blind beyond that distance. When the animated object drops to 0 hit points, it reverts to its original object form, and any remaining damage carries over to its original object form. If you command an object to attack, it can make a single melee attack against a creature within 5 feet of it. It makes a slam attack with an attack bonus and bludgeoning damage determined by its size. The GM might rule that a specific object inflicts slashing or piercing damage based on its form. At Higher Levels. If you cast this spell using a spell slot of 6th level or higher, you can animate two additional objects for each slot level above 5th.",
  },
  {
    name: "Antagonize",
    spellClass: ["Warlock", "Bard", "Sorcerer", "Wizard"],
    lvl: "3",
    school: "Evocation",
    range: "30ft",
    castingTime: "1 action",
    duration: "Instantaneous",
    concentration: false,
    ritual: false,
    saveThrow: "WIS",
    damageType: "psychic",
    components: ["V", "S", "M"],
    materials: "a drop of blood, a piece of flesh, and a pinch of bone dust",
    description:
      "You whisper magical words that antagonize one creature of your choice within range. The target must make a Wisdom saving throw. On a failed save, the target takes 4d4 psychic damage and must immediately use its reaction to make a melee attack against another creature of your choice that you can see. If the target can\u2109t make this attack (for example, because there is no one within its reach or because its reaction is unavailable), the target instead has disadvantage on the next attack roll it makes before the start of your next turn. On a successful save, the target takes half as much damage only. At Higher Levels. When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d4 for each slot level above 3rd.",
  },
  {
    name: "Antilife Shell",
    spellClass: ["Death Domain", "Grave Domain", "Druid"],
    lvl: "5",
    school: "Abjuration",
    range: "self 10ft sphere",
    castingTime: "1 action",
    duration: "1 hour",
    concentration: true,
    ritual: false,
    saveThrow: "",
    damageType: "",
    components: ["V", "S"],
    description:
      "A shimmering barrier extends out from you in a 10-foot radius and moves with you, remaining centered on you and hedging out creatures other than undead and constructs. The barrier lasts for the duration. The barrier prevents an affected creature from passing or reaching through. An affected creature can cast spells or make attacks with ranged or reach weapons through the barrier. If you move so that an affected creature is forced to pass through the barrier, the spell ends.",
  },
  {
    name: "Antimagic Field",
    spellClass: ["Cleric", "Wizard"],
    lvl: "8",
    school: "Abjuration",
    range: "self 10ft sphere",
    castingTime: "1 action",
    duration: "1 hour",
    concentration: true,
    ritual: false,
    components: ["V", "S", "M"],
    materials: "a pinch of powdered iron or iron filings",
    description:
      "A 10-foot-radius invisible sphere of antimagic surrounds you. This area is divorced from the magical energy that suffuses the multiverse. Within the sphere, spells can't be cast, summoned creatures disappear, and even magic items become mundane. Until the spell ends, the sphere moves with you, centered on you. Spells and other magical effects, except those created by an artifact or a deity, are suppressed in the sphere and can't protrude into it. A slot expended to cast a suppressed spell is consumed. While an effect is suppressed, it doesn't function, but the time it spends suppressed counts against its duration. Targeted Effects: Spells and other magical effects, such as magic missile and charm person, that target a creature or an object in the sphere have no effect on that target. Areas of Magic: The area of another spell or magical effect, such as fireball, can't extend into the sphere. If the sphere overlaps an area of magic, the part of the area that is covered by the sphere is suppressed. For example, the flames created by a wall of fire are suppressed within the sphere, creating a gap in the wall if the overlap is large enough. Spells: Any active spell or other magical effect on a creature or an object in the sphere is suppressed while the creature or object is in it. Magic Items: The properties and powers of magic items are suppressed in the sphere. For example, a +1 long sword in the sphere functions as a nonmagical long sword. A magic weapon's properties and powers are suppressed if it is used against a target in the sphere or wielded by an attacker in the sphere. If a magic weapon or piece of magic ammunition fully leaves the sphere (For example, if you fire a magic arrow or throw a magic spear at a target outside the sphere), the magic of the item ceases to be suppressed as soon as it exits. Magical Travel: Teleportation and planar travel fail to work in the sphere, whether the sphere is the destination or the departure point for such magical travel. A portal to another location, world, or plane of existence, as well as an opening to an extradimensional space such as that created by the rope trick spells, temporarily closes while in the sphere. Creatures and Objects: A creature or object summoned or created by magic temporarily winks out of existence in the sphere. Such a creature instantly reappears once the space the creature occupied is no longer within the sphere. Dispel Magic: Spells and magical effects such as dispel magic have no effect on the sphere. Likewise, the spheres created by different antimagic field spells don't nullify each other.",
  },
  {
    name: "Antipathy/Sympathy",
    spellClass: ["Druid", "Wizard"],
    lvl: "8",
    school: "Enchantment",
    range: "60 ft 200ft cube",
    castingTime: "1 Hour",
    duration: "10 days",
    concentration: false,
    ritual: false,
    components: ["V", "S", "M"],
    materials:
      "either a lump of alum soaked in vinegar for the antipathy effect or a drop of honey for the sympathy effect",
    description:
      "This spell attracts or repels creatures of your choice. You target something within range, either a Huge or smaller object or creature or an area that is no larger than a 200-foot cube. Then specify a kind of intelligent creature, such as red dragons, goblins, or vampires. You invest the target with an aura that either attracts or repels the specified creatures for the duration. Choose antipathy or sympathy as the aura's effect. Antipathy. The enchantment causes creatures of the kind you designated to feel an intense urge to leave the area and avoid the target. When such a creature can see the target or comes within 60 feet of it, the creature must succeed on a Wisdom saving throw or become frightened. The creature remains frightened while it can see the target or is within 60 feet of it. While frightened by the target, the creature must use its movement to move to the nearest safe spot from which it can't see the target. If the creature moves more than 60 feet from the target and can't see it, the creature is no longer frightened, but the creature becomes frightened again if it regains sight of the target or moves within 60 feet of it. Sympathy. The enchantment causes the specified creatures to feel an intense urge to approach the target while within 60 feet of it or able to see it. When such a creature can see the target or comes within 60 feet of it, the creature must succeed on a Wisdom saving throw or use its movement on each of its turns to enter the area or move within reach of the target. When the creature has done so, it can't willingly move away from the target. If the target damages or otherwise harms an affected creature, the affected creature can make a Wisdom saving throw to end the effect, as described below. Ending the Effect. If an affected creature ends its turn while not within 60 feet of the target or able to see it, the creature makes a Wisdom saving throw. On a successful save, the creature is no longer affected by the target and recognizes the feeling of repugnance or attraction as magical. In addition, a creature affected by the spell is allowed another Wisdom saving throw every 24 hours while the spell persists. A creature that successfully saves against this effect is immune to it for 1 minute, after which time it can be affected again.",
  },
  {
    name: "Arcane Eye",
    spellClass: ["Artificer", "Wizard", "Knowledge Domain", "Arcana Domain"],
    lvl: "4",
    school: "Divination",
    range: "30ft",
    castingTime: "1 Action",
    duration: "1 hour",
    concentration: true,
    ritual: false,
    components: ["V", "S", "M"],
    materials: "a bit of bat fur",
    description:
      "You create an invisible, magical eye within range that hovers in the air for the duration. You mentally receive visual information from the eye, which has normal vision and darkvision out to 30 feet. The eye can look in every direction. As an action, you can move the eye up to 30 feet in any direction. There is no limit to how far away from you the eye can move, but it can't enter another plane of existence. A solid barrier blocks the eye's movement, but the eye can pass through an opening as small as 1 inch in diameter.",
  },
  {
    name: "Arcane Gate",
    spellClass: ["Sorcerer", "Wizard", "Warlock"],
    lvl: "6",
    school: "Conjuration",
    range: "500ft",
    castingTime: "1 Action",
    duration: "10 minutes",
    concentration: true,
    ritual: false,
    components: ["V", "S"],
    description:
      "You create linked teleportation portals that remain open for the duration. Choose two points on the ground that you can see, one point within 10 feet of you and one point within 500 feet of you. A circular portal, 10 feet in diameter, opens over each point. If the portal would open in the space occupied by a creature, the spell fails, and the casting is lost. The portals are two-dimensional glowing rings filled with mist, hovering inches from the ground and perpendicular to it at the points you choose. A ring is visible only from one side (your choice), which is the side that functions as a portal. Any creature or object entering the portal exits from the other portal as if the two were adjacent to each other; passing through a portal from the nonportal side has no effect. The mist that fills each portal is opaque and blocks vision through it. On your turn, you can rotate the rings as a bonus action so that the active side faces in a different direction.",
  },
  {
    name: "Arcane Hand",
    spellClass: ["Wizard"],
    lvl: "5",
    school: "Evocation",
    range: "120ft",
    castingTime: "1 Action",
    duration: "1 minute",
    concentration: true,
    ritual: false,
    components: ["V", "S", "M"],
    materials: "an eggshell and a snakeskin glove",
    description:
      "You create a Large hand of shimmering, translucent force in an unoccupied space that you can see within range. The hand lasts for the spell's duration, and it moves at your command, mimicking the movements of your own hand. The hand is an object that has AC 20 and hit points equal to your hit point maximum. If it drops to 0 hit points, the spell ends. It has a Strength of 26 (+8) and a Dexterity of 10 (+0). The hand doesn't fill its space. When you cast the spell and as a bonus action on your subsequent turns, you can move the hand up to 60 feet and then cause one of the following effects with it. Clenched Fist. The hand strikes one creature or object within 5 feet of it. Make a melee spell attack for the hand using your game statistics. On a hit, the target takes 4d8 force damage. Forceful Hand. The hand attempts to push a creature within 5 feet of it in a direction you choose. Make a check with the hand's Strength contested by the Strength (Athletics) check of the target. If the target is Medium or smaller, you have advantage on the check. If you succeed, the hand pushes the target up to 5 feet plus a number of feet equal to five times your spellcasting ability modifier. The hand moves with the target to remain within 5 feet of it. Grasping Hand. The hand attempts to grapple a Huge or smaller creature within 5 feet of it. You use the hand's Strength score to resolve the grapple. If the target is Medium or smaller, you have advantage on the check. While the hand is grappling the target, you can use a bonus action to have the hand crush it. When you do so, the target takes bludgeoning damage equal to 2d6 + your spellcasting ability modifier. Interposing Hand. The hand interposes itself between you and a creature you choose until you give the hand a different command. The hand moves to stay between you and the target, providing you with half cover against the target. The target can't move through the hand's space if its Strength score is less than or equal to the hand's Strength score. If its Strength score is higher than the hand's Strength score, the target can move toward you through the hand's space, but that space is difficult terrain for the target. At Higher Levels. When you cast this spell using a spell slot of 6th level or higher, the damage from the clenched fist option increases by 2d8 and the damage from the grasping hand increases by 2d6 for each slot level above 5th.",
  },
  {
    name: "Arcane Lock",
    spellClass: ["Wizard", "Artificer"],
    lvl: "2",
    school: "Abjuration",
    range: "touch",
    castingTime: "1 Action",
    duration: "Until Dispelled",
    concentration: false,
    ritual: false,
    components: ["V", "S", "M"],
    materials: "gold dust worth at least 25 gp, which the spell consumes",
    description:
      "You touch a closed door, window, gate, chest, or other entryway, and it becomes locked for the duration. You and the creatures you designate when you cast this spell can open the object normally. You can also set a password that, when spoken within 5 feet of the object, suppresses this spell for 1 minute. Otherwise, it is impassable until it is broken or the spell is dispelled or suppressed. Casting knock on the object suppresses arcane lock for 10 minutes. While affected by this spell, the object is more difficult to break or force open; the DC to break it or pick any locks on it increases by 10.",
  },
  {
    name: "Arcanist's Magic Aura",
    spellClass: ["Wizard", "Arcana Domain"],
    lvl: "2",
    school: "Illusion",
    range: "touch",
    castingTime: "1 Action",
    duration: "24 Hours",
    concentration: false,
    ritual: false,
    components: ["V", "S", "M"],
    materials: "gold dust worth at least 25 gp, which the spell consumes",
    description:
      "You place an illusion on a creature or an object you touch so that divination spells reveal false information about it. The target can be a willing creature or an object that isn't being carried or worn by another creature. When you cast the spell, choose one or both of the following effects. The effect lasts for the duration. If you cast this spell on the same creature or object every day for 30 days, placing the same effect on it each time, the illusion lasts until it is dispelled. False Aura. You change the way the target appears to spells and magical effects, such as detect magic, that detect magical auras. You can make a nonmagical object appear magical, a magical object appear nonmagical, or change the object's magical aura so that it appears to belong to a specific school of magic that you choose. When you use this effect on an object, you can make the false magic apparent to any creature that handles the item. Mask. You change the way the target appears to spells and magical effects that detect creature types, such as a paladin's Divine Sense or the trigger of a symbol spell. You choose a creature type and other spells and magical effects treat the target as if it were a creature of that type or of that alignment.",
  },
  {
    name: "Armor of Agathys",
    spellClass: ["Warlock"],
    lvl: "1",
    school: "Abjuration",
    range: "Self",
    castingTime: "1 Action",
    duration: "1 Hour",
    concentration: false,
    ritual: false,
    components: ["V", "S", "M"],
    materials: "a cup of water",
    description:
      "A protective magical force surrounds you, manifesting as a spectral frost that covers you and your gear. You gain 5 temporary hit points for the duration. If a creature hits you with a melee attack while you have these hit points, the creature takes 5 cold damage. At Higher Levels. When you cast this spell using a spell slot of 2nd level or higher, both the temporary hit points and the cold damage increase by 5 for each slot.",
  },
  {
    name: "Arms of Hadar",
    spellClass: ["Warlock"],
    lvl: "1",
    school: "Conjuration",
    range: "Self 10ft radius",
    castingTime: "1 Action",
    duration: "Instantaneous",
    concentration: false,
    ritual: false,
    components: ["V", "S"],
    description:
      "You invoke the power of Hadar, the Dark Hunger. Tendrils of dark energy erupt from you and batter all creatures within 10 feet of you. Each creature in that area must make a Strength saving throw. On a failed save, a target takes 2d6 necrotic damage and can\u2109t take reactions until its next turn. On a successful save, the creature takes half damage, but suffers no other effect. At Higher Levels. When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d6 for each slot level above 1st.",
  },
  {
    name: "Ashardalon's Stride",
    spellClass: ["Artificer", "Ranger", "Sorcerer", "Wizard"],
    lvl: "3",
    school: "Transmutation",
    range: "Self",
    castingTime: "1 Bonus Action",
    duration: "1 minute",
    concentration: true,
    ritual: false,
    components: ["V", "S"],
    description:
      "The billowing flames of a dragon blast from your feet, granting you explosive speed. For the duration, your speed increases by 20 feet and moving doesn\u2019t provoke opportunity attacks. When you move within 5 feet of a creature or an object that isn\u2109t being worn or carried, it takes 1d6 fire damage from your trail of heat. A creature or object can take this damage only once during a turn. At Higher Levels. When you cast this spell using a spell slot of 4th level or higher, increase your speed by 5 feet for each spell slot level above 3rd. The spell deals an additional 1d6 fire damage for each slot level above 3rd.",
  },
  {
    name: "Astral Projection",
    spellClass: ["Cleric", "Warlock", "Wizard"],
    lvl: "9",
    school: "Necromancy",
    range: "10ft",
    castingTime: "1 Hour",
    duration: "Special",
    concentration: false,
    ritual: false,
    components: ["V", "S", "M"],
    materials:
      "for each creature you affect with this spell, you must provide one jacinth worth at least 1,000 gp and one ornately carved bar of silver worth at least 100 gp, all of which the spell consumes",
    description:
      "You and up to eight willing creatures within range project your astral bodies into the Astral Plane (the spell fails and the casting is wasted if you are already on that plane). The material body you leave behind is unconscious and in a state of suspended animation; it doesn't need food or air and doesn't age. Your astral body resembles your mortal form in almost every way, replicating your game statistics and possessions. The principal difference is the addition of a silvery cord that extends from between your shoulder blades and trails behind you, fading to invisibility after 1 foot. This cord is your tether to your material body. As long as the tether remains intact, you can find your way home. If the cord is cut--something that can happen only when an effect specifically states that it does--your soul and body are separated, killing you instantly. Your astral form can freely travel through the Astral Plane and can pass through portals there leading to any other plane. If you enter a new plane or return to the plane you were on when casting this spell, your body and possessions are transported along the silver cord, allowing you to re-enter your body as you enter the new plane. Your astral form is a separate incarnation. Any damage or other effects that apply to it have no effect on your physical body, nor do they persist when you return to it. The spell ends for you and your companions when you use your action to dismiss it. When the spell ends, the affected creature returns to its physical body, and it awakens. The spell might also end early for you or one of your companions. A successful dispel magic spell used against an astral or physical body ends the spell for that creature. If a creature's original body or its astral form drops to 0 hit points, the spell ends for that creature. If the spell ends and the silver cord is intact, the cord pulls the creature's astral form back to its body, ending its state of suspended animation.If you are returned to your body prematurely, your companions remain in their astral forms and must find their own way back to their bodies, usually by dropping to 0 hit points.",
  },
  {
    name: "Augury",
    spellClass: ["Cleric", "Oath of the Open Sea"],
    lvl: "2",
    school: "Divination",
    range: "self",
    castingTime: "1 Minute",
    duration: "Instantaneous",
    concentration: false,
    ritual: true,
    components: ["V", "S", "M"],
    materials:
      "specially marked sticks, bones, or similar tokens worth at least 25 gp",
    description:
      "By casting gem-inlaid sticks, rolling dragon bones, laying out ornate cards, or employing some other divining tool, you receive an omen from an otherworldly entity about the results of a specific course of action that you plan to take within the next 30 minutes. The DM chooses from the following possible omens: Weal, for good results. Woe, for bad results. Weal and woe, for both good and bad results. Nothing, for results that aren't especially good or bad. The spell doesn't take into account any possible circumstances that might change the outcome, such as the casting of additional spells or the loss or gain of a companion. If you cast the spell two or more times before completing your next long rest, there is a cumulative 25 percent chance for each casting after the first that you get a random reading. The DM makes this roll in secret.",
  },
  {
    name: "Aura of Life",
    spellClass: ["Cleric", "Paladin"],
    lvl: "4",
    school: "Abjuration",
    range: "self 30ft radius",
    castingTime: "1 action",
    duration: "10 minutes",
    concentration: true,
    ritual: false,
    components: ["V"],
    description:
      "Life-preserving energy radiates from you in an aura with a 30-foot radius. Until the spell ends, the aura moves with you, centered on you. Each non-hostile creature in the aura (including you) has resistance to necrotic damage, and its hit point maximum can\u2109t be reduced. In addition, a non-hostile, living creature regains 1 hit point when it starts its turn in the aura with 0 hit points.",
  },
  {
    name: "Aura of Purity",
    spellClass: ["Cleric", "Paladin"],
    lvl: "4",
    school: "Abjuration",
    range: "self 30ft radius",
    castingTime: "1 action",
    duration: "10 minutes",
    concentration: true,
    ritual: false,
    components: ["V"],
    description:
      "Purifying energy radiates from you in an aura with a 30-foot radius. Until the spell ends, the aura moves with you, centered on you. Each non-hostile creature in the aura (including you) can\u2129t become diseased, has resistance to poison damage, and has advantage on saving throws against effects that cause any of the following conditions: blinded, charmed, deafened, frightened, paralyzed, poisoned, and stunned.",
  },
  {
    name: "Aura of Vitality",
    spellClass: ["Cleric", "Paladin", "Druid"],
    lvl: "3",
    school: "Evocation",
    range: "self 30ft radius",
    castingTime: "1 action",
    duration: "10 minutes",
    concentration: true,
    ritual: false,
    components: ["V"],
    description:
      "Healing energy radiates from you in an aura with a 30-foot radius. Until the spell ends, the aura moves with you, centered on you. You can use a bonus action to cause one creature in the aura (including you) to regain 2d6 hit points.",
  },
  {
    name: "Awaken",
    spellClass: ["Cleric", "Paladin", "Druid"],
    lvl: "5",
    school: "Transmutation",
    range: "touch",
    castingTime: "18 hours",
    duration: "Instantaneous",
    concentration: false,
    ritual: false,
    components: ["V", "S", "M"],
    materials: "an agate worth at least 1,000 gp, which the spell consumes",
    description:
      "After spending the casting time tracing magical pathways within a precious gemstone, you touch a Huge or smaller beast or plant. The target must have either no Intelligence score or an Intelligence of 3 or less. The target gains an Intelligence of 10. The target also gains the ability to speak one language you know. If the target is a plant, it gains the ability to move its limbs, roots, vines, creepers, and so forth, and it gains senses similar to a human's. Your GM chooses statistics appropriate for the awakened plant, such as the statistics for the awakened shrub or the awakened tree. The awakened beast or plant is charmed by you for 30 days or until you or your companions do anything harmful to it. When the charmed condition ends, the awakened creature chooses whether to remain friendly to you, based on how you treated it while it was charmed.",
  },
  {
    name: "Bane",
    spellClass: ["Bard", "Cleric", "Oath of Vengeance"],
    lvl: "1",
    school: "Enchantment",
    range: "30 ft",
    castingTime: "1 Action",
    duration: "1 minute",
    concentration: true,
    ritual: false,
    components: ["V", "S", "M"],
    materials: "a drop of blood",
    description:
      "Up to three creatures of your choice that you can see within range must make Charisma saving throws. Whenever a target that fails this saving throw makes an attack roll or a saving throw before the spell ends, the target must roll a d4 and subtract the number rolled from the attack roll or saving throw. At Higher Levels. When you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st.",
  },
  {
    name: "Banishing Smite",
    spellClass: ["Paladin"],
    lvl: "5",
    school: "Abjuation",
    range: "self",
    castingTime: "1 Bonus Action",
    duration: "1 minute",
    concentration: true,
    ritual: false,
    components: ["V"],
    description:
      "The next time you hit a creature with a weapon attack before this spell ends, your weapon crackles with force, and the attack deals an extra 5d10 force damage to the target. Additionally, if this attack reduces the target to 50 hit points of fewer, you banish it. If the target is native to a different plane of existence than the on you\u2019re on, the target disappears, returning to its home plane. If the target is native to the plane you\u20109re on, the creature vanishes into a harmless demiplane. While there, the target is incapacitated. It remains there until the spell ends, at which point the target reappears in the space it left or in the nearest unoccupied space if that space is occupied.",
  },
  {
    name: "Banishment",
    spellClass: ["Paladin", "Cleric", "Sorcerer", "Warlock", "Wizard"],
    lvl: "4",
    school: "Abjuation",
    range: "60 ft",
    castingTime: "1 Action",
    duration: "1 minute",
    concentration: true,
    ritual: false,
    saveThrow: "CHA",
    components: ["V", "S", "M"],
    materials: "an item distasteful to the target",
    description:
      "You attempt to send one creature that you can see within range to another plane of existence. The target must succeed on a Charisma saving throw or be banished. If the target is native to the plane of existence you\u20109re on, you banish the target to a harmless demiplane. While there, the target is incapacitated. The target remains there until the spell ends, at which point the target reappears in the space it left or in the nearest unoccupied space if that space is occupied. If the target is native to a different plane of existence than the one you\u2109re on, the target is banished with a faint popping noise, returning to its home plane. If the spell ends before 1 minute has passed, the target reappears in the space it left or in the nearest unoccupied space if that space is occupied. Otherwise, the target doesn\u20109t return. At Higher Levels. When you cast this spell using a spell slot of 5th level or higher, you can target one additional creature for each slot level above 4th.",
  },
  {
    name: "Barkskin",
    spellClass: ["Druid", "Ranger", "Nature Domain"],
    lvl: "2",
    school: "Transmutation",
    range: "touch",
    castingTime: "1 Action",
    duration: "1 Hour",
    concentration: true,
    ritual: false,
    components: ["V", "S", "M"],
    materials: "a handful of oak bark",
    description:
      "You touch a willing creature. Until the spell ends, the target's skin has a rough, bark-like appearance, and the target's AC can't be less than 16, regardless of what kind of armor it is wearing.",
  },
  {
    name: "Beacon of Hope",
    spellClass: ["Cleric"],
    lvl: "3",
    school: "Abjuration",
    range: "30 ft",
    castingTime: "1 Action",
    duration: "1 minute",
    concentration: true,
    ritual: false,
    components: ["V", "S"],
    description:
      "This spell bestows hope and vitality. Choose any number of creatures within range. For the duration, each target has advantage on Wisdom saving throws and death saving throws, and regains the maximum number of hit points possible from any healing.",
  },
  {
    name: "Beast Bond",
    spellClass: ["Druid", "Ranger"],
    lvl: "1",
    school: "Divination",
    range: "touch",
    castingTime: "1 Action",
    duration: "10 minutes",
    concentration: true,
    ritual: false,
    components: ["V", "S", "M"],
    materials: "a bit of fur wrapped in a cloth",
    description:
      "You establish a telepathic link with one beast you touch that is friendly to you or charmed by you. The spell fails if the beast\u2019s Intelligence is 4 or higher. Until the spell ends, the link is active while you and the beast are within line of sight of each other. Through the link, the beast can understand your telepathic messages to it, and it can telepathically communicate simple emotions and concepts back to you. While the link is active, the beast gains advantage on attack rolls against any creature within 5 feet of you that you can see.",
  },
  {
    name: "Beast Sense",
    spellClass: ["Druid", "Ranger"],
    lvl: "2",
    school: "Divination",
    range: "touch",
    castingTime: "1 Action",
    duration: "1 Hour",
    concentration: true,
    ritual: true,
    components: ["S"],
    materials: "a bit of fur wrapped in a cloth",
    description:
      "You touch a willing beast. For the duration of the spell, you can use your action to see through the beast\u2019s eyes and hear what it hears, and continue to do so until you use your action to return to your normal senses.",
  },
  {
    name: "Bestow Curse",
    spellClass: ["Cleric", "Bard", "Wizard", "Oathbreaker", "Oath of Conquest"],
    lvl: "3",
    school: "Necromancy",
    range: "touch",
    castingTime: "1 Action",
    duration: "1 minute",
    concentration: true,
    ritual: false,
    saveThrow: "WIS",
    components: ["V", "S"],
    description:
      "You touch a creature, and that creature must succeed on a Wisdom saving throw or become cursed for the duration of the spell. When you cast this spell, choose the nature of the curse from the following options: Choose one ability score. While cursed, the target has disadvantage on ability checks and saving throws made with that ability score. While cursed, the target has disadvantage on attack rolls against you. While cursed, the target must make a Wisdom saving throw at the start of each of its turns. If it fails, it wastes its action that turn doing nothing. While the target is cursed, your attacks and spells deal an extra 1d8 necrotic damage to the target. A remove curse spell ends this effect. At the DM's option, you may choose an alternative curse effect, but it should be no more powerful than those described above. The DM has final say on such a curse's effect. At Higher Levels. If you cast this spell using a spell slot of 4th level or higher, the duration is concentration, up to 10 minutes. If you use a spell slot of 5th level or higher, the duration is 8 hours. If you use a spell slot of 7th level or higher, the duration is 24 hours. If you use a 9th level spell slot, the spell lasts until it is dispelled. Using a spell slot of 5th level or higher grants a duration that doesn't require concentration.",
  },
  {
    name: "Bigby's Hand",
    spellClass: ["Arificer", "Sorcerer", "Wizard"],
    lvl: "5",
    school: "evocation",
    range: "120 ft",
    castingTime: "1 Action",
    duration: "1 minute",
    concentration: true,
    ritual: false,
    components: ["V", "S", "M"],
    materials: "an eggshell and a snakeskin glove",
    description:
      "You create a Large hand of shimmering, translucent force in an unoccupied space that you can see within range. The hand lasts for the spell\u2019s duration, and it moves at your command, mimicking the movements of your own hand. The hand is an object that has AC 20 and hit points equal to your hit point maximum. If it drops to 0 hit points, the spell ends. It has a Strength of 26 (+8) and a Dexterity of 10 (+0). The hand doesn\u2019t fill its space. When you cast the spell and as a bonus action on your subsequent turns, you can move the hand up to 60 feet and then cause one of the following effects with it. Clenched Fist. The hand strikes one creature or object within 5 feet of it. Make a melee spell attack for the hand using your game statistics. On a hit, the target takes 4d8 force damage. Forceful Hand. The hand attempts to push a creature within 5 feet of it in a direction you choose. Make a check with the hand\u2019s Strength contested by the Strength (Athletics) check of the target. If the target is Medium or smaller, you have advantage on the check. If you succeed, the hand pushes the target up to 5 feet plus a number of feet equal to five times your spellcasting ability modifier. The hand moves with the target to remain within 5 feet of it. Grasping Hand. The hand attempts to grapple a Huge or smaller creature within 5 feet of it. You use the hand\u2019s Strength score to resolve the grapple. If the target is Medium or smaller, you have advantage on the check. While the hand is grappling the target, you can use a bonus action to have the hand crush it. When you do so, the target takes bludgeoning damage equal to 2d6 + your spellcasting ability modifier. Interposing Hand. The hand interposes itself between you and a creature you choose until you give the hand a different command. The hand moves to stay between you and the target, providing you with half cover against the target. The target can\u2019t move through the hand\u2019s space if its Strength score is less than or equal to the hand\u2019s Strength score. If its Strength score is higher than the hand\u2019s Strength score, the target can move toward you through the hand\u2019s space, but that space is difficult terrain for the target. At Higher Levels. When you cast this spell using a spell slot of 6th level or higher, the damage from the clenched fist option increases by 2d8 and the damage from the grasping hand increases by 2d6 for each slot level above 5th.",
  },
  {
    name: "Black Tentacles",
    spellClass: ["Warlock", "Wizard"],
    lvl: "4",
    school: "Conjuration",
    range: "90ft 20ft cube",
    castingTime: "1 Action",
    duration: "1 minute",
    concentration: true,
    ritual: false,
    saveThrow: "DEX",
    components: ["V", "S", "M"],
    materials: "a piece of tentacle from a giant octopus or a giant squid",
    description:
      "Squirming, ebony tentacles fill a 20-foot square on ground that you can see within range. For the duration, these tentacles turn the ground in the area into difficult terrain. When a creature enters the affected area for the first time on a turn or starts its turn there, the creature must succeed on a Dexterity saving throw or take 3d6 bludgeoning damage and be restrained by the tentacles until the spell ends. A creature that starts its turn in the area and is already restrained by the tentacles takes 3d6 bludgeoning damage. A creature restrained by the tentacles can use its action to make a Strength or Dexterity check (its choice) against your spell save DC. On a success, it frees itself.",
  },
  {
    name: "Blade Barrier",
    spellClass: ["Cleric"],
    lvl: "6",
    school: "Evocation",
    range: "90ft",
    castingTime: "1 Action",
    duration: "10 minutes",
    concentration: true,
    ritual: false,
    saveThrow: "DEX",
    components: ["V", "S"],
    description:
      "You create a vertical wall of whirling, razor-sharp blades made of magical energy. The wall appears within range and lasts for the duration. You can make a straight wall up to 100 feet long, 20 feet high, and 5 feet thick, or a ringed wall up to 60 feet in diameter, 20 feet high, and 5 feet thick. The wall provides three-quarters cover to creatures behind it, and its space is difficult terrain. When a creature enters the wall's area for the first time on a turn or starts its turn there, the creature must make a Dexterity saving throw. On a failed save, the creature takes 6d10 slashing damage. On a successful save, the creature takes half as much damage.",
  },
  {
    name: "Blade of Disaster",
    spellClass: ["Sorcerer", "Warlock", "Wizard"],
    lvl: "9",
    school: "conjuration",
    range: "60 ft",
    castingTime: "1 Bonus Action",
    duration: "1 minute",
    concentration: true,
    ritual: false,
    components: ["V", "S"],
    description:
      "You create a blade-shaped planar rift about 3 feet long in an unoccupied space you can see within range. The blade lasts for the duration. When you cast this spell, you can make up to two melee spell attacks with the blade, each one against a creature, loose object, or structure within 5 feet of the blade. On a hit, the target takes 4d12 force damage. This attack scores a critical hit if the number on the d20 is 18 or higher. On a critical hit, the blade deals an extra 8d12 force damage (for a total of 12d12 force damage). As a bonus action on your turn, you can move the blade up to 30 feet to an unoccupied space you can see and then make up to two melee spell attacks with it again. The blade can harmlessly pass through any barrier, including a Wall of Force.",
  },
  {
    name: "Blade Ward",
    spellClass: ["Sorcerer", "Warlock", "Wizard", "Bard"],
    lvl: "cantrip",
    school: "Abjuration ",
    range: "self",
    castingTime: "1 Action",
    duration: "1 round",
    concentration: false,
    ritual: false,
    components: ["V", "S"],
    description:
      "You extend your hand and trace a sigil of warding in the air. Until the end of your next turn, you have resistance against bludgeoning, piercing, and slashing damage dealt by weapon attacks.",
  },
  {
    name: "Bless",
    spellClass: ["Cleric", "Paladin"],
    lvl: "1",
    school: "Enchantment ",
    range: "30 ft",
    castingTime: "1 Action",
    duration: "1 minute",
    concentration: true,
    ritual: false,
    components: ["V", "S", "M"],
    materials: "a sprinkling of holy water",
    description:
      "You bless up to three creatures of your choice within range. Whenever a target makes an attack roll or a saving throw before the spell ends, the target can roll a d4 and add the number rolled to the attack roll or saving throw. At Higher Levels. When you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st.",
  },
  {
    name: "Blight",
    spellClass: [
      "Druid",
      "Sorcerer",
      "Warlock",
      "Wizard",
      "Death Domain",
      "Grave Domain",
      "Blood Domain",
      "Oathbreaker",
      "Alchemist",
    ],
    lvl: "4",
    school: "Necromancy",
    range: "30ft",
    castingTime: "1 Action",
    duration: "Instantaneous",
    concentration: false,
    ritual: false,
    saveThrow: "CON",
    damageType: "Necrotic",
    components: ["V", "S"],
    description:
      "Necromantic energy washes over a creature of your choice that you can see within range, draining moisture and vitality from it. The target must make a Constitution saving throw. The target takes 8d8 necrotic damage on a failed save, or half as much damage on a successful one. This spell has no effect on undead or constructs. If you target a plant creature or a magical plant, it makes the saving throw with disadvantage, and the spell deals maximum damage to it. If you target a nonmagical plant that isn't a creature, such as a tree or shrub, it doesn't make a saving throw; it simply withers and dies. At Higher Levels. When you cast this spell using a spell slot of 5th level or higher, the damage increases by 1d8 for each slot level above 4th.",
  },
  {
    name: "Blinding Smite",
    spellClass: ["Paladin"],
    lvl: "3",
    school: "evocation",
    range: "self",
    castingTime: "1 Bonus Action",
    duration: "1 minute",
    concentration: true,
    ritual: false,
    saveThrow: "CON",
    damageType: "Radiant",
    components: ["V"],
    description:
      "The next time you hit a creature with a melee weapon attack during this spell\u2109s duration, you weapon flares with a bright light, and the attack deals an extra 3d8 radiant damage to the target. Additionally, the target must succeed on a Constitution saving throw or be blinded until the spell ends. A creature blinded by this spell makes another Constitution saving throw at the end of each of its turns. On a successful save, it is no longer blinded.",
  },
  {
    name: "Blindness/Deafness",
    spellClass: [
      "Bard",
      "Cleric",
      "Sorcerer",
      "Wizard",
      "Death Domain",
      "Warlock",
    ],
    lvl: "2",
    school: "Necromancy",
    range: "30 ft",
    castingTime: "1 Action",
    duration: "1 minute",
    concentration: false,
    ritual: false,
    saveThrow: "CON",
    components: ["V"],
    description:
      "You can blind or deafen a foe. Choose one creature that you can see within range to make a Constitution saving throw. If it fails, the target is either blinded or deafened (your choice) for the duration. At the end of each of its turns, the target can make a Constitution saving throw. On a success, the spell ends.At Higher Levels. When you cast this spell using a spell slot of 3rd level or higher, you can target one additional creature for each slot level above 2nd.",
  },
  {
    name: "Blink",
    spellClass: [
      "Sorcerer",
      "Wizard",
      "Artificer",
      "Trickery Domain",
      "Warlock",
    ],
    lvl: "3",
    school: "Transmutation",
    range: "self",
    castingTime: "1 Action",
    duration: "1 minute",
    concentration: false,
    ritual: false,
    components: ["V", "S"],
    description:
      "Roll a d20 at the end of each of your turns for the duration of the spell. On a roll of 11 or higher, you vanish from your current plane of existence and appear in the Ethereal Plane (the spell fails and the casting is wasted if you were already on that plane). At the start of your next turn, and when the spell ends if you are on the Ethereal Plane, you return to an unoccupied space of your choice that you can see within 10 feet of the space you vanished from. If no unoccupied space is available within that range, you appear in the nearest unoccupied space (chosen at random if more than one space is equally near). You can dismiss this spell as an action. While on the Ethereal Plane, you can see and hear the plane you originated from, which is cast in shades of gray, and you can't see anything there more than 60 feet away. You can only affect and be affected by other creatures on the Ethereal Plane. Creatures that aren't there can't perceive you or interact with you, unless they have the ability to do so.",
  },
  {
    name: "Blur",
    spellClass: ["Sorcerer", "Wizard", "Artificer", "Warlock"],
    lvl: "2",
    school: "Illusion",
    range: "self",
    castingTime: "1 Action",
    duration: "1 minute",
    concentration: true,
    ritual: false,
    components: ["V"],
    description:
      "Your body becomes blurred, shifting and wavering to all who can see you. For the duration, any creature has disadvantage on attack rolls against you. An attacker is immune to this effect if it doesn't rely on sight, as with blindsight, or can see through illusions, as with truesight.",
  },
  {
    name: "Bones of the Earth",
    spellClass: ["Druid"],
    lvl: "6",
    school: "Transmutation",
    range: "120 ft 5ft cylinder",
    castingTime: "1 Action",
    duration: "Instantaneous",
    concentration: false,
    ritual: false,
    saveThrow: "DEX",
    components: ["V", "S"],
    description:
      "You cause up to six pillars of stone to burst from places on the ground that you can see within range. Each pillar is a cylinder that has a diameter of 5 feet and a height of up to 30 feet. The ground where a pillar appears must be wide enough for its diameter, and you can target the ground under a creature if that creature is Medium or smaller. Each pillar has AC 5 and 30 hit points. When reduced to 0 hit points, a pillar crumbles into rubble, which creates an area of difficult terrain with a 10-foot radius that lasts until the rubble is cleared. Each 5-foot-diameter portion of the area requires at least 1 minute to clear by hand. If a pillar is created under a creature, that creature must succeed on a Dexterity saving throw or be lifted by the pillar. A creature can choose to fail the save. If a pillar is prevented from reaching its full height because of a ceiling or other obstacle, a creature on the pillar takes 6d6 bludgeoning damage and is restrained, pinched between the pillar and the obstacle. The restrained creature can use an action to make a Strength or Dexterity check (the creature\u20109s choice) against the spell\u2019s save DC. On a success, the creature is no longer restrained and must either move off the pillar or fall off it. At Higher Levels. When you cast this spell using a spell slot of 7th level or higher, you can create two additional pillars for each slot level above 6th.",
  },
  {
    name: "Booming Blade",
    spellClass: ["Artificer", "Sorcerer", "Warlock", "Wizard"],
    lvl: "cantrip",
    school: "Evocation",
    range: "self",
    castingTime: "1 Action",
    duration: "1 round",
    concentration: false,
    ritual: false,
    components: ["S", "M"],
    materials: "a melee weapon worth at least 1 sp",
    description:
      "You brandish the weapon used in the spell\u2109s casting and make a melee attack with it against one creature within 5 feet of you. On a hit, the target suffers the weapon attack\u2109s normal effects and then becomes sheathed in booming energy until the start of your next turn. If the target willingly moves 5 feet or more before then, the target takes 1d8 thunder damage, and the spell ends. At Higher Levels. At 5th level, the melee attack deals an extra 1d8 thunder damage to the target on a hit, and the damage the target takes for moving increases to 2d8. Both damage rolls increase by 1d8 at 11th level (2d8 and 3d8) and again at 17th level (3d8 and 4d8).",
  },
  {
    name: "Borrowed Knowledge",
    spellClass: ["Bard", "Cleric", "Warlock", "Wizard"],
    lvl: "2",
    school: "Divination",
    range: "self",
    castingTime: "1 Action",
    duration: "1 round",
    concentration: false,
    ritual: false,
    components: ["V", "S", "M"],
    materials: "a book worth at least 25 gp",
    description:
      "You draw on knowledge from spirits of the past. Choose one skill in which you lack proficiency. For the spell's duration, you have proficiency in the chosen skill. The spell ends early if you cast it again.",
  },
  {
    name: "Branding Smite",
    spellClass: ["Paladin"],
    lvl: "2",
    school: "Evocation",
    range: "self",
    castingTime: "1 Bonus Action",
    duration: "1 minute",
    concentration: true,
    ritual: false,
    components: ["V"],
    description:
      "The next time you hit a creature with a weapon attack before this spell ends, the weapon gleams with astral radiance as you strike. The attack deals an extra 2d6 radiant damage to the target, which becomes visible if it is invisible, and the target sheds dim light in a 5-foot radius and can’t become invisible until the spell ends. At Higher Levels. When you cast this spell using a spell slot of 3rd level or higher, the extra damage increases by 1d6 for each slot level above 2nd.",
  },
  {
    name: "Burning Hands",
    spellClass: ["Sorcerer", "Wizard", "Light Domain", "Warlock", "Druid"],
    lvl: "1",
    school: "Evocation",
    range: "self 15ft cone",
    castingTime: "1 Action",
    duration: "Instantaneous",
    concentration: false,
    ritual: false,
    saveThrow: "DEX",
    damageType: "Fire",
    components: ["V", "S"],
    description:
      "As you hold your hands with thumbs touching and fingers spread, a thin sheet of flames shoots forth from your outstretched fingertips. Each creature in a 15-foot cone must make a Dexterity saving throw. A creature takes 3d6 fire damage on a failed save, or half as much damage on a successful one. The fire ignites any flammable objects in the area that aren't being worn or carried. At Higher Levels. When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d6 for each slot level above 1st.",
  },
  {
    name: "Call Lightning",
    spellClass: ["Druid"],
    lvl: "3",
    school: "Conjuration",
    range: "120 ft 60ft cylinder",
    castingTime: "1 Action",
    duration: "10 minutes",
    concentration: true,
    ritual: false,
    saveThrow: "DEX",
    damageType: "Lightning",
    components: ["V", "S"],
    description:
      "A storm cloud appears in the shape of a cylinder that is 10 feet tall with a 60-foot radius, centered on a point you can see within range directly above you. The spell fails if you can\u21109t see a point in the air where the storm cloud could appear (for example, if you are in a room that can\u20109t accommodate the cloud). When you cast the spell, choose a point you can see under the cloud. A bolt of lightning flashes down from the cloud to that point. Each creature within 5 feet of that point must make a Dexterity saving throw. A creature takes 3d10 lightning damage on a failed save, or half as much damage on a successful one. On each of your turns until the spell ends, you can use your action to call down lightning in this way again, targeting the same point or a different one. If you are outdoors in stormy conditions when you cast this spell, the spell gives you control over the existing storm instead of creating a new one. Under such conditions, the spell\u21109s damage increases by 1d10. At Higher Levels. When you cast this spell using a spell slot of 4th or higher level, the damage increases by 1d10 for each slot level above 3rd.",
  },
  {
    name: "Calm Emotions",
    spellClass: ["Warlock", "Bard", "Cleric", "Oath of Redemption"],
    lvl: "2",
    school: "Enchantment",
    range: "60 ft 20ft sphere",
    castingTime: "1 Action",
    duration: "1 minute",
    concentration: true,
    ritual: false,
    saveThrow: "CHA",
    components: ["V", "S"],
    description:
      "You attempt to suppress strong emotions in a group of people. Each humanoid in a 20-foot-radius sphere centered on a point you choose within range must make a Charisma saving throw; a creature can choose to fail this saving throw if it wishes. If a creature fails its saving throw, choose one of the following two effects. You can suppress any effect causing a target to be charmed or frightened. When this spell ends, any suppressed effect resumes, provided that its duration has not expired in the meantime. Alternatively, you can make a target indifferent about creatures of your choice that it is hostile toward. This indifference ends if the target is attacked or harmed by a spell or if it witnesses any of its friends being harmed. When the spell ends, the creature becomes hostile again, unless the DM rules otherwise.",
  },
  {
    name: "Catapult",
    spellClass: ["Artificer", "Sorcerer", "Wizard"],
    lvl: "1",
    school: "Transmutation",
    range: "60 ft",
    castingTime: "1 Action",
    duration: "Instantaneous",
    concentration: false,
    ritual: false,
    saveThrow: "DEX",
    components: ["S"],
    description:
      "Choose one object weighing 1 to 5 pounds within range that isn\u2019t being worn or carried. The object flies in a straight line up to 90 feet in a direction you choose before falling to the ground, stopping early if it impacts against a solid surface. If the object would strike a creature, that creature must make a Dexterity saving throw. On a failed save, the object strikes the target and stops moving. When the object strikes something, the object and what it strikes each take 3d8 bludgeoning damage. At Higher Levels. When you cast this spell using a spell slot of 2nd level or higher, the maximum weight of objects that you can target with this spell increases by 5 pounds, and the damage increases by 1d8, for each slot level above 1st.",
  },
  {
    name: "Catnap",
    spellClass: ["Artificer", "Sorcerer", "Wizard", "Bard"],
    lvl: "3",
    school: "Enchantment",
    range: "30 ft",
    castingTime: "1 Action",
    duration: "10 minutes",
    concentration: false,
    ritual: false,
    components: ["S", "M"],
    materials: "a pinch of sand",
    description:
      "You make a calming gesture, and up to three willing creatures of your choice that you can see within range fall unconscious for the spell\u2109s duration. The spell ends on a target early if it takes damage or someone uses an action to shake or slap it awake. If a target remains unconscious for the full duration, that target gains the benefit of a short rest, and it can\u2109t be affected by this spell again until it finishes a long rest.",
  },
  {
    name: "Cause Fear",
    spellClass: ["Warlock", "Wizard"],
    lvl: "1",
    school: "necromancy",
    range: "60 ft",
    castingTime: "1 action",
    duration: "1 minute",
    concentration: true,
    ritual: false,
    saveThrow: "WIS",
    components: ["V"],
    description:
      "You awaken the sense of mortality in one creature you can see within range. A construct or an undead is immune to this effect. The target must succeed on a Wisdom saving throw or become frightened of you until the spell ends. The frightened target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success. At Higher Levels. When you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st. The creatures must be within 30 feet of each other when you target them.",
  },
  {
    name: "Ceremony",
    spellClass: ["Cleric", "Paladin"],
    lvl: "1",
    school: "evocation ",
    range: "touch",
    castingTime: "1 hour",
    duration: "Instantaneous ",
    concentration: false,
    ritual: true,
    components: ["V", "S", "M"],
    materials: "25 gp worth of powdered silver, which the spell consumes",
    description:
      "You perform one of several religious ceremonies. When you cast the spell, choose one of the following ceremonies, the target of which must be within 10 feet of you throughout the casting. Atonement. You touch one willing creature whose alignment has changed, and you make a DC 20 Wisdom (Insight) check. On a successful check, you restore the target to its original alignment. Bless Water. You touch one vial of water and cause it to become holy water. Coming of Age. You touch one humanoid who is a young adult. For the next 24 hours, whenever the target makes an ability check, it can roll a d4 and add the number rolled to the ability check. A creature can benefit from this rite only once.  Dedication. You touch one humanoid who wishes to be dedicated to your god\u2109s service. For the next 24 hours, whenever the target makes a saving throw, it can roll a d4 and add the number rolled to the save. A creature can benefit from this rite only once. Funeral Rite. You touch one corpse, and for the next 7 days, the target can\u2109t become undead by any means short of a Wish spell. Investiture (UA). You touch one willing humanoid. Choose one 1st-level spell you have prepared and expend a spell slot and any material components as if you were casting that spell. The spell has no effect. Instead, the target can cast this spell once without having to expend a spell slot or use material components. If the target doesn\u2109t cast the spell within 1 hour, the invested spell is lost. Wedding. You touch adult humanoids willing to be bonded together in marriage. For the next 7 days, each target gains a +2 bonus to AC while they are within 30 feet of each other. A creature can benefit from this rite again only if widowed.",
  },
  {
    name: "Chain Lightning",
    spellClass: ["Wizard", "Sorcerer"],
    lvl: "6",
    school: "Evocation ",
    range: "150 ft",
    castingTime: "1 action",
    duration: "Instantaneous ",
    concentration: false,
    ritual: false,
    saveThrow: "DEX",
    damageType: "lightning",
    components: ["V", "S", "M"],
    materials:
      "a bit of fur; a piece of amber, glass, or a crystal rod; and three silver pins",
    description:
      "You create a bolt of lightning that arcs toward a target of your choice that you can see within range. Three bolts then leap from that target to as many as three other targets, each of which must be within 30 feet of the first target. A target can be a creature or an object and can be targeted by only one of the bolts. A target must make a Dexterity saving throw. The target takes 10d8 lightning damage on a failed save, or half as much damage on a successful one. At Higher Levels. When you cast this spell using a spell slot of 7th level or higher, one additional bolt leaps from the first target to another target for each slot level above 6th.",
  },
  {
    name: "Chaos Bolt",
    spellClass: ["Sorcerer"],
    lvl: "1",
    school: "Evocation ",
    range: "120 ft",
    castingTime: "1 action",
    duration: "Instantaneous ",
    concentration: false,
    ritual: false,
    components: ["V", "S"],
    description:
      "You hurl an undulating, warbling mass of chaotic energy at one creature in range. Make a ranged spell attack against the target. On a hit, the target takes 2d8 + 1d6 damage. Choose one of the d8s. The number rolled on that die determines the attack's damage type, as shown below. 1: Acid. 2: Cold. 3: Fire. 4: Force. 5: Lightning. 6: Posion. 7: Psychic. 8: Thunder. If you roll the same number on both d8s, the chaotic energy leaps from the target to a different creature of your choice within 30 feet of it. Make a new attack roll against the new target, and make a new damage roll, which could cause the chaotic energy to leap again. A creature can be targeted only once by each casting of this spell. At Higher Levels. When you cast this spell using a spell slot of 2nd level or higher, each target takes 1d6 extra damage of the type rolled for each slot level above 1st.",
  },
  {
    name: "Charm Monster",
    spellClass: ["Sorcerer", "Bard", "Druid", "Warlock", "Wizard"],
    lvl: "4",
    school: "Enchantment ",
    range: "30 ft",
    castingTime: "1 action",
    duration: "1 hour ",
    concentration: false,
    ritual: false,
    saveThrow: "WIS",
    components: ["V", "S"],
    description:
      "You attempt to charm a creature you can see within range. It must make a Wisdom saving throw, and it does so with advantage if you or your companions are fighting it. If it fails the saving throw, it is charmed by you until the spell ends or until you or your companions do anything harmful to it. The charmed creature is friendly to you. When the spell ends, the creature knows it was charmed by you. At Higher Levels. When you cast this spell using a spell slot of 5th level or higher, you can target one additional creature for each slot level above 4th. The creatures must be within 30 feet of each other when you target them.",
  },
  {
    name: "Charm Person",
    spellClass: [
      "Sorcerer",
      "Bard",
      "Druid",
      "Warlock",
      "Wizard",
      "Trickery Domain",
    ],
    lvl: "1",
    school: "Enchantment ",
    range: "30 ft",
    castingTime: "1 action",
    duration: "1 hour ",
    concentration: false,
    ritual: false,
    saveThrow: "WIS",
    components: ["V", "S"],
    description:
      "You attempt to charm a humanoid you can see within range. It must make a Wisdom saving throw, and does so with advantage if you or your companions are fighting it. If it fails the saving throw, it is charmed by you until the spell ends or until you or your companions do anything harmful to it. The charmed creature regards you as a friendly acquaintance. When the spell ends, the creature knows it was charmed by you. At Higher Levels. When you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st. The creatures must be within 30 feet of each other when you target them.",
  },
  {
    name: "Chill Touch",
    spellClass: ["Sorcerer", "Warlock", "Wizard"],
    lvl: "cantrip",
    school: "Necromancy ",
    range: "120 ft",
    castingTime: "1 action",
    duration: "1 Round",
    concentration: false,
    ritual: false,
    saveThrow: "WIS",
    components: ["V", "S"],
    description:
      "You create a ghostly, skeletal hand in the space of a creature within range. Make a ranged spell attack against the creature to assail it with the chill of the grave. On a hit, the target takes 1d8 necrotic damage, and it can't regain hit points until the start of your next turn. Until then, the hand clings to the target. If you hit an undead target, it also has disadvantage on attack rolls against you until the end of your next turn. This spell's damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).",
  },
  {
    name: "Chromatic Orb",
    spellClass: ["Sorcerer", "Wizard"],
    lvl: "1",
    school: "Evocation",
    range: "90 ft",
    castingTime: "1 action",
    duration: "Instantaneous",
    concentration: false,
    ritual: false,
    components: ["V", "S", "M"],
    materials: "a diamond worth at least 50 gp",
    description:
      "You hurl a 4-inch-diameter sphere of energy at a creature that you can see within range. You choose acid, cold, fire, lightning, poison, or thunder for the type of orb you create, and then make a ranged spell attack against the target. If the attack hits, the creature takes 3d8 damage of the type you chose. At Higher Levels. When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d8 for each slot level above 1st.",
  },
  {
    name: "Circle of Death",
    spellClass: ["Sorcerer", "Wizard", "Warlock"],
    lvl: "6",
    school: "Necromancy",
    range: "150 ft 60ft sphere",
    castingTime: "1 action",
    duration: "Instantaneous",
    concentration: false,
    ritual: false,
    saveThrow: "CON",
    damageType: "Necrotic",
    components: ["V", "S", "M"],
    materials: "the powder of a crushed black pearl worth at least 500 gp",
    description:
      "A sphere of negative energy ripples out in a 60-foot-radius sphere from a point within range. Each creature in that area must make a Constitution saving throw. A target takes 8d6 necrotic damage on a failed save, or half as much damage on a successful one. At Higher Levels. When you cast this spell using a spell slot of 7th level or higher, the damage increases by 2d6 for each slot level above 6th.",
  },
  {
    name: "Circle of Power",
    spellClass: ["Paladin"],
    lvl: "5",
    school: "abjuration",
    range: "self 30ft radius",
    castingTime: "1 action",
    duration: "10 minutes",
    concentration: true,
    ritual: false,
    components: ["V"],
    description:
      "Divine energy radiates from you, distorting and diffusing magical energy within 30 feet of you. Until the spell ends, the sphere moves with you, centered on you. For the duration, each friendly creature in the area (including you) has advantage on saving throws against spells and other magical effects. Additionally, when an affected creature succeeds on a saving throw made against a spell or magical effect that allows it to make a saving throw to take only half damage, it instead takes no damage if it succeeds on the saving throws.",
  },
  {
    name: "Clairvoyance",
    spellClass: ["Warlock", "Bard", "Cleric", "Sorcerer", "Wizard"],
    lvl: "3",
    school: "Divination",
    range: "1 mile",
    castingTime: "1o minutes",
    duration: "10 minutes",
    concentration: true,
    ritual: false,
    components: ["V", "S", "M"],
    materials:
      "a focus worth at least 100 gp, either a jeweled horn for hearing or a glass eye for seeing",
    description:
      "You create an invisible sensor within range in a location familiar to you (a place you have visited or seen before) or in an obvious location that is unfamiliar to you (such as behind a door, around a corner, or in a grove of trees). The sensor remains in place for the duration, and it can't be attacked or otherwise interacted with. When you cast the spell, you choose seeing or hearing. You can use the chosen sense through the sensor as if you were in its space. As your action, you can switch between seeing and hearing. A creature that can see the sensor (such as a creature benefiting from see invisibility or truesight) sees a luminous, intangible orb about the size of your fist.",
  },
  {
    name: "Clone",
    spellClass: ["Wizard"],
    lvl: "8",
    school: "Necromancy",
    range: "touch",
    castingTime: "1 hour",
    duration: "Instantaneous",
    concentration: false,
    ritual: false,
    components: ["V", "S", "M"],
    materials:
      "a diamond worth at least 1,000 gp and at least 1 cubic inch of flesh of the creature that is to be cloned, which the spell consumes, and a vessel worth at least 2,000 gp that has a sealable lid and is large enough to hold the creature being cloned, such as a huge urn, coffin, mud- filled cyst in the ground, or crystal container filled with salt water",
    description:
      "This spell grows an inert duplicate of a living creature as a safeguard against death. This clone forms inside the vessel used in the spell\u2019s casting and grows to full size and maturity after 120 days; you can also choose to have the clone be a younger version of the same creature. It remains inert and endures indefinitely, as long as its vessel remains undisturbed. At any time after the clone matures, if the original creature dies, its soul transfers to the clone, provided that the soul is free and willing to return. The clone is physically identical to the original and has the same personality, memories, and abilities, but none of the original's equipment. The original creature's physical remains, if they still exist, become inert and can't thereafter be restored to life, since the creature's soul is elsewhere.",
  },
  {
    name: "Cloud of Daggers",
    spellClass: ["Wizard", "Bard", "Sorcerer", "Warlock"],
    lvl: "2",
    school: "conjuration",
    range: "60 ft 5ft cube",
    castingTime: "1 action",
    duration: "1 minute",
    concentration: true,
    ritual: false,
    components: ["V", "S", "M"],
    materials: "A sliver of glass",
    description:
      "You fill the air with spinning daggers in a cube 5 feet on each side, centered on a point you choose within range. A creature takes 4d4 slashing damage when it enters the spell\u2109s area for the first time on a turn or starts its turn there. At Higher Levels. When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 2d4 for each slot level above 2nd",
  },
  {
    name: "Cloudkill",
    spellClass: [
      "Wizard",
      "Alchemist",
      "Sorcerer",
      "Death Domain",
      "Oath of Conquest",
      "Warlock",
    ],
    lvl: "2",
    school: "conjuration",
    range: "120 ft 20ft sphere",
    castingTime: "1 action",
    duration: "10 minutes",
    concentration: true,
    ritual: false,
    saveThrow: "CON",
    damageType: "Posion",
    components: ["V", "S"],
    description:
      "You create a 20-foot-radius sphere of poisonous, yellow-green fog centered on a point you choose within range. The fog spreads around corners. It lasts for the duration or until strong wind disperses the fog, ending the spell. Its area is heavily obscured. When a creature enters the spell's area for the first time on a turn or starts its turn there, that creature must make a Constitution saving throw. The creature takes 5d8 poison damage on a failed save, or half as much damage on a successful one. Creatures are affected even if they hold their breath or don't need to breathe. The fog moves 10 feet away from you at the start of each of your turns, rolling along the surface of the ground. The vapors, being heavier than air, sink to the lowest level of the land, even pouring down openings. At Higher Levels. When you cast this spell using a spell slot of 6th level or higher, the damage increases by 1d8 for each slot level above 5th.",
  },
  {
    name: "Color Spray",
    spellClass: ["Wizard", "Sorcerer"],
    lvl: "1",
    school: "Illusion",
    range: "self 15ft cone",
    castingTime: "1 action",
    duration: "1 round",
    concentration: false,
    ritual: false,
    components: ["V", "S", "M"],
    materials:
      "a pinch of powder or sand that is colored red, yellow, and blue",
    description:
      "A dazzling array of flashing, colored light springs from your hand. Roll 6d10; the total is how many hit points of creatures this spell can affect. Creatures in a 15-foot cone originating from you are affected in ascending order of their current hit points (ignoring unconscious creatures and creatures that can\u2109t see). Starting with the creature that has the lowest current hit points, each creature affected by this spell is blinded until the end of your next turn. Subtract each creature\u2109s hit points from the total before moving on to the creature with the next lowest hit points. A creature\u2109s hit points must be equal to or less than the remaining total for that creature to be affected. At Higher Levels. When you cast this spell using a spell slot of 2nd level or higher, roll an additional 2d10 for each slot level above 1st.",
  },
  {
    name: "Command",
    spellClass: [
      "Cleric",
      "Paladin",
      "Warlock",
      "Oath of the Crown",
      "Oath of Conquest",
    ],
    lvl: "1",
    school: "Enchantment",
    range: "60 ft",
    castingTime: "1 action",
    duration: "1 round",
    concentration: false,
    ritual: false,
    saveThrow: "WIS",
    components: ["V"],
    description:
      "You speak a one-word command to a creature you can see within range. The target must succeed on a Wisdom saving throw or follow the command on its next turn. The spell has no effect if the target is undead, if it doesn't understand your language, or if your command is directly harmful to it. Some typical commands and their effects follow. You might issue a command other than one described here. If you do so, the DM determines how the target behaves. If the target can't follow your command, the spell ends. Approach. The target moves toward you by the shortest and most direct route, ending its turn if it moves within 5 feet of you. Drop. The target drops whatever it is holding and then ends its turn. Flee. The target spends its turn moving away from you by the fastest available means. Grovel. The target falls prone and then ends its turn. Halt. The target doesn't move and takes no actions. A flying creature stays aloft, provided that it is able to do so. If it must move to stay aloft, it flies the minimum distance needed to remain in the air. At Higher Levels. When you cast this spell using a spell slot of 2nd level or higher, you can affect one additional creature for each slot level above 1st. The creatures must be within 30 feet of each other when you target them.",
  },
  {
    name: "Commune",
    spellClass: ["Cleric", "Paladin"],
    lvl: "5",
    school: "Divination",
    range: "self",
    castingTime: "1 minute",
    duration: "1 minute",
    concentration: false,
    ritual: true,
    components: ["V", "S", "M"],
    materials: "incense and a vial of holy or unholy water",
    description:
      "You contact your deity or a divine proxy and ask up to three questions that can be answered with a yes or no. You must ask your questions before the spell ends. You receive a correct answer for each question. Divine beings aren't necessarily omniscient, so you might receive 'unclear' as an answer if a question pertains to information that lies beyond the deity's knowledge. In a case where a one-word answer could be misleading or contrary to the deity's interests, the GM might offer a short phrase as an answer instead. If you cast the spell two or more times before finishing your next long rest, there is a cumulative 25 percent chance for each casting after the first that you get no answer. The GM makes this roll in secret.",
  },
  {
    name: "Commune with Nature",
    spellClass: [
      "Druid",
      "Ranger",
      "Oath of the Open Sea",
      "Oath of the Ancients",
    ],
    lvl: "5",
    school: "Divination",
    range: "self",
    castingTime: "1 minute",
    duration: "Instantaneous",
    concentration: false,
    ritual: true,
    components: ["V", "S"],
    description:
      "You briefly become one with nature and gain knowledge of the surrounding territory. In the outdoors, the spell gives you knowledge of the land within 3 miles of you. In caves and other natural underground settings, the radius is limited to 300 feet. The spell doesn't function where nature has been replaced by construction, such as in dungeons and towns. You instantly gain knowledge of up to three facts of your choice about any of the following subjects as they relate to the area: terrain and bodies of water. Prevalent plants, minerals, animals, or peoples powerful celestials, fey, fiends, elementals, or undead. Influence from other planes of existence. Buildings. For example, you could determine the location of powerful undead in the area, the location of major sources of safe drinking water, and the location of any nearby towns.",
  },
  {
    name: "Compelled Duel",
    spellClass: ["Paladin"],
    lvl: "1",
    school: "enchantment",
    range: "30ft",
    castingTime: "1 minute",
    duration: "Instantaneous",
    concentration: true,
    ritual: false,
    saveThrow: "WIS",
    components: ["V"],
    description:
      "You attempt to compel a creature into a duel. One creature that you can see within range must make a Wisdom saving throw. On a failed save, the creature is drawn to you, compelled by your divine demand. For the duration, it has disadvantage on attack rolls against creatures other than you, and must make a Wisdom saving throw each time it attempts to move to a space that is more than 30 feet away from you; if it succeeds on this saving throw, this spell doesn\u2109t restrict the target\u2109s movement for that turn. The spell ends if you attack any other creature, if you cast a spell that targets a hostile creature other than the target, if a creature friendly to you damages the target or casts a harmful spell on it, or if you end your turn more than 30 feet away from the target.",
  },
  {
    name: "Comprehend Languages",
    spellClass: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    lvl: "1",
    school: "Divination",
    range: "sef",
    castingTime: "1 action",
    duration: "1 hour",
    concentration: fasle,
    ritual: true,
    components: ["V", "S", "M"],
    materials: "a pinch of soot and salt",
    description:
      "For the duration, you understand the literal meaning of any spoken language that you hear. You also understand any written language that you see, but you must be touching the surface on which the words are written. It takes about 1 minute to read one page of text. This spell doesn't decode secret messages in a text or a glyph, such as an arcane sigil, that isn't part of a written language.",
  },
];

async function seedSpells() {
  try {
    const existingSpells = await Spell.find({});

    for (const spell of spellData) {
      const isExisting = existingSpells.some(
        (existingSpell) => existingSpell.name === spell.name
      );
      if (!isExisting) {
        await Spell.create(spell);
        console.log(`spell added: ${spell.name}`);
      } else {
        await Spell.findOneAndUpdate({ name: spell.name }, spell);
        console.log(`${spell.name} updated.`);
      }
    }
  } catch (err) {
    console.error("Error seeding spells", err);
  }
}

module.exports = { seedSpells };
